set search_path = public, extensions;

create extension if not exists postgis with schema extensions;

create table if not exists public.rutas (
  id integer generated by default as identity primary key,
  codigo_ctp text,
  operador text,
  nombre_ruta text,
  canton_inicio text,
  canton_final text,
  distancia_km double precision,
  "año_ramal" text,
  geometry jsonb
);

create index if not exists idx_rutas_codigo_ctp
  on public.rutas (codigo_ctp);

create index if not exists idx_rutas_canton
  on public.rutas (canton_inicio);

create table if not exists public.ruta_puntos (
  id integer generated by default as identity primary key,
  ruta_id integer references public.rutas(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  orden integer not null,
  geog geography(Point, 4326),
  segmento_id integer not null default 0
);

create index if not exists idx_ruta_puntos_ruta_id
  on public.ruta_puntos (ruta_id);

create index if not exists idx_ruta_puntos_segmento
  on public.ruta_puntos (ruta_id, segmento_id, orden);

create index if not exists idx_ruta_puntos_geog
  on public.ruta_puntos
  using gist (geog);

create index if not exists ruta_puntos_geo_gix
  on public.ruta_puntos
  using gist (((st_setsrid(st_makepoint(lng, lat), 4326))::geography));

create table if not exists public.tarifas (
  id integer generated by default as identity primary key,
  ruta_id integer references public.rutas(id) on delete set null,
  codigo_ruta text,
  nombre_ruta text,
  nombre_fraccionamiento text,
  km_promedio numeric,
  tarifa_regular integer,
  tarifa_adulto_mayor integer,
  resolucion text,
  fecha_vigencia date,
  operador text,
  cedula_operador text,
  creado_en timestamptz default now()
);

create index if not exists idx_tarifas_ruta_id
  on public.tarifas (ruta_id);

create index if not exists idx_tarifas_codigo_ruta
  on public.tarifas (codigo_ruta);

create index if not exists idx_tarifas_vigencia
  on public.tarifas (fecha_vigencia desc);

alter table public.rutas enable row level security;
alter table public.tarifas enable row level security;

grant select on public.rutas to anon, authenticated;
grant select on public.tarifas to anon, authenticated;

drop policy if exists rutas_read_public on public.rutas;
create policy rutas_read_public
on public.rutas
for select
to anon, authenticated
using (true);

drop policy if exists tarifas_read_anon on public.tarifas;
create policy tarifas_read_anon
on public.tarifas
for select
to anon
using (true);

drop policy if exists tarifas_read_auth on public.tarifas;
create policy tarifas_read_auth
on public.tarifas
for select
to authenticated
using (true);

comment on table public.rutas is
  'Tabla base legacy de rutas. Bootstrap para ambientes nuevos antes de aplicar el resto de migraciones del planner.';

comment on table public.ruta_puntos is
  'Puntos ordenados del trazado legacy por ruta. Usado para mapa, backups y reconstruccion de geometria.';

comment on table public.tarifas is
  'Tarifas legacy por ruta y fecha de vigencia. La app las consulta directo para mostrar costo estimado.';
