set search_path = public, extensions;

create table if not exists public.planner_service_groups (
  id bigint generated by default as identity primary key,
  group_key text not null unique,
  group_name text not null,
  group_type text not null default 'preferred_alternatives',
  description text,
  priority integer not null default 100,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_service_groups_type_chk
    check (group_type in ('preferred_alternatives', 'equivalent_destination', 'equivalent_origin', 'transfer_bundle')),
  constraint planner_service_groups_priority_chk
    check (priority >= 0)
);

create index if not exists planner_service_groups_lookup_idx
  on public.planner_service_groups (activo, priority, group_type);

create table if not exists public.planner_service_group_members (
  id bigint generated by default as identity primary key,
  service_group_id bigint not null references public.planner_service_groups(id) on delete cascade,
  product_route_id integer,
  preview_route_id integer references public.rutas(id) on delete set null,
  route_code text not null,
  variant_family_code text,
  variant_code text,
  member_label text not null,
  service_role text not null default 'both',
  member_priority integer not null default 100,
  directness_rank integer not null default 100,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_service_group_members_role_chk
    check (service_role in ('origin', 'destination', 'both')),
  constraint planner_service_group_members_priority_chk
    check (member_priority >= 0),
  constraint planner_service_group_members_directness_chk
    check (directness_rank >= 0)
);

create unique index if not exists planner_service_group_members_uidx
  on public.planner_service_group_members (
    service_group_id,
    route_code,
    coalesce(variant_family_code, ''),
    coalesce(variant_code, ''),
    member_label,
    service_role
  );

create index if not exists planner_service_group_members_lookup_idx
  on public.planner_service_group_members (service_group_id, activo, member_priority, directness_rank);

create index if not exists planner_service_group_members_route_idx
  on public.planner_service_group_members (route_code, product_route_id, preview_route_id)
  where activo = true;

create table if not exists public.planner_hub_service_groups (
  id bigint generated by default as identity primary key,
  hub_id bigint not null references public.planner_hubs(id) on delete cascade,
  service_group_id bigint not null references public.planner_service_groups(id) on delete cascade,
  role text not null default 'destination',
  priority integer not null default 100,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_hub_service_groups_role_chk
    check (role in ('origin', 'destination', 'both')),
  constraint planner_hub_service_groups_priority_chk
    check (priority >= 0),
  constraint planner_hub_service_groups_uidx
    unique (hub_id, service_group_id, role)
);

create index if not exists planner_hub_service_groups_lookup_idx
  on public.planner_hub_service_groups (hub_id, role, activo, priority);

drop trigger if exists set_updated_at_planner_service_groups on public.planner_service_groups;
create trigger set_updated_at_planner_service_groups
before update on public.planner_service_groups
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_planner_service_group_members on public.planner_service_group_members;
create trigger set_updated_at_planner_service_group_members
before update on public.planner_service_group_members
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_planner_hub_service_groups on public.planner_hub_service_groups;
create trigger set_updated_at_planner_hub_service_groups
before update on public.planner_hub_service_groups
for each row execute function public.set_updated_at();

alter table public.planner_service_groups enable row level security;
alter table public.planner_service_group_members enable row level security;
alter table public.planner_hub_service_groups enable row level security;

grant select on public.planner_service_groups to anon, authenticated;
grant select on public.planner_service_group_members to anon, authenticated;
grant select on public.planner_hub_service_groups to anon, authenticated;

drop policy if exists planner_service_groups_read_public on public.planner_service_groups;
create policy planner_service_groups_read_public
on public.planner_service_groups
for select
to anon, authenticated
using (true);

drop policy if exists planner_service_group_members_read_public on public.planner_service_group_members;
create policy planner_service_group_members_read_public
on public.planner_service_group_members
for select
to anon, authenticated
using (true);

drop policy if exists planner_hub_service_groups_read_public on public.planner_hub_service_groups;
create policy planner_hub_service_groups_read_public
on public.planner_hub_service_groups
for select
to anon, authenticated
using (true);

create or replace function public.planner_resolve_service_group_candidates(
  p_origin_lat double precision,
  p_origin_lng double precision,
  p_destination_lat double precision,
  p_destination_lng double precision
)
returns table (
  origin_hub_key text,
  origin_hub_name text,
  destination_hub_key text,
  destination_hub_name text,
  group_key text,
  group_name text,
  group_type text,
  route_code text,
  product_route_id integer,
  preview_route_id integer,
  variant_family_code text,
  variant_code text,
  member_label text,
  member_priority integer,
  directness_rank integer,
  effective_priority integer,
  metadata jsonb
)
language sql
stable
set search_path = public, extensions
as $$
with origin_point as (
  select st_setsrid(st_makepoint(p_origin_lng, p_origin_lat), 4326)::geography as geo
),
destination_point as (
  select st_setsrid(st_makepoint(p_destination_lng, p_destination_lat), 4326)::geography as geo
),
origin_hubs as (
  select
    h.id,
    h.hub_key,
    h.hub_name,
    h.priority,
    st_distance(h.geo, op.geo)::integer as distance_m
  from public.planner_hubs h
  cross join origin_point op
  where h.activo = true
    and st_dwithin(h.geo, op.geo, h.radius_m)
),
destination_hubs as (
  select
    h.id,
    h.hub_key,
    h.hub_name,
    h.priority,
    st_distance(h.geo, dp.geo)::integer as distance_m
  from public.planner_hubs h
  cross join destination_point dp
  where h.activo = true
    and st_dwithin(h.geo, dp.geo, h.radius_m)
),
destination_groups as (
  select
    dh.hub_key as destination_hub_key,
    dh.hub_name as destination_hub_name,
    hsg.service_group_id,
    hsg.priority as destination_priority,
    dh.priority as destination_hub_priority,
    dh.distance_m as destination_hub_distance_m
  from destination_hubs dh
  join public.planner_hub_service_groups hsg
    on hsg.hub_id = dh.id
   and hsg.activo = true
   and hsg.role in ('destination', 'both')
),
origin_groups as (
  select
    oh.hub_key as origin_hub_key,
    oh.hub_name as origin_hub_name,
    hsg.service_group_id,
    hsg.priority as origin_priority,
    oh.priority as origin_hub_priority,
    oh.distance_m as origin_hub_distance_m
  from origin_hubs oh
  join public.planner_hub_service_groups hsg
    on hsg.hub_id = oh.id
   and hsg.activo = true
   and hsg.role in ('origin', 'both')
),
origin_scoped_groups as (
  select distinct service_group_id
  from public.planner_hub_service_groups
  where activo = true
    and role in ('origin', 'both')
)
select
  og.origin_hub_key,
  og.origin_hub_name,
  dg.destination_hub_key,
  dg.destination_hub_name,
  sg.group_key,
  sg.group_name,
  sg.group_type,
  gm.route_code,
  gm.product_route_id,
  gm.preview_route_id,
  gm.variant_family_code,
  gm.variant_code,
  gm.member_label,
  gm.member_priority,
  gm.directness_rank,
  (
    sg.priority
    + dg.destination_priority
    + dg.destination_hub_priority
    + least(dg.destination_hub_distance_m, 500) / 25
    + coalesce(og.origin_priority, 0)
    + coalesce(og.origin_hub_priority, 0)
    + coalesce(least(og.origin_hub_distance_m, 500) / 25, 0)
    + gm.member_priority
    + gm.directness_rank
  )::integer as effective_priority,
  jsonb_strip_nulls(
    sg.metadata
    || jsonb_build_object(
      'member_metadata', gm.metadata,
      'origin_required', (osg.service_group_id is not null)
    )
  ) as metadata
from destination_groups dg
join public.planner_service_groups sg
  on sg.id = dg.service_group_id
 and sg.activo = true
join public.planner_service_group_members gm
  on gm.service_group_id = sg.id
 and gm.activo = true
 and gm.service_role in ('destination', 'both')
left join origin_groups og
  on og.service_group_id = sg.id
left join origin_scoped_groups osg
  on osg.service_group_id = sg.id
where osg.service_group_id is null
   or og.service_group_id is not null
order by effective_priority asc, gm.member_priority asc, gm.directness_rank asc, gm.member_label asc;
$$;

grant execute on function public.planner_resolve_service_group_candidates(
  double precision,
  double precision,
  double precision,
  double precision
) to anon, authenticated;

drop view if exists public.planner_service_group_member_qa;
create or replace view public.planner_service_group_member_qa as
select
  sg.group_key,
  sg.group_name,
  sg.group_type,
  sg.priority as group_priority,
  gm.member_label,
  gm.route_code,
  gm.product_route_id,
  gm.preview_route_id,
  gm.variant_family_code,
  gm.variant_code,
  gm.member_priority,
  gm.directness_rank,
  gm.activo as member_active,
  ph.hub_key,
  ph.hub_name,
  hsg.role as hub_role,
  hsg.priority as hub_priority,
  r.nombre_ruta as preview_route_name
from public.planner_service_groups sg
join public.planner_service_group_members gm
  on gm.service_group_id = sg.id
left join public.planner_hub_service_groups hsg
  on hsg.service_group_id = sg.id
left join public.planner_hubs ph
  on ph.id = hsg.hub_id
left join public.rutas r
  on r.id = gm.preview_route_id
order by sg.priority asc, sg.group_name asc, gm.member_priority asc, gm.directness_rank asc;

grant select on public.planner_service_group_member_qa to anon, authenticated;

comment on table public.planner_service_groups is
  'Grupos de servicio para destinos donde varias rutas sirven, pero con preferencia interna (por ejemplo, una via mas directa).';

comment on table public.planner_service_group_members is
  'Miembros de un grupo de servicio. Permite mezclar ids productivos, ids preview y familias oficiales CTP.';

comment on table public.planner_hub_service_groups is
  'Vincula hubs de origen/destino con grupos de servicio para que el planner sugiera familias equivalentes por zona.';

comment on function public.planner_resolve_service_group_candidates(double precision, double precision, double precision, double precision) is
  'Resuelve candidatos de grupos de servicio segun hubs de origen/destino, respetando preferencias y rutas mas directas.';

comment on view public.planner_service_group_member_qa is
  'Vista QA para revisar como quedan vinculados hubs, grupos de servicio y sus rutas preferidas.';
