set search_path = public, extensions;

create table if not exists public.planner_hubs (
  id bigint generated by default as identity primary key,
  hub_key text not null unique,
  hub_name text not null,
  hub_type text not null,
  lat numeric not null,
  lng numeric not null,
  geo geography(Point, 4326) generated always as (
    st_setsrid(st_makepoint((lng)::double precision, (lat)::double precision), 4326)::geography
  ) stored,
  radius_m integer not null default 250,
  planner_radius_override_m integer,
  priority integer not null default 100,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_hubs_type_chk
    check (hub_type in ('terminal', 'center', 'landmark', 'district', 'hospital', 'transfer')),
  constraint planner_hubs_radius_chk
    check (radius_m between 25 and 2000),
  constraint planner_hubs_override_radius_chk
    check (planner_radius_override_m is null or planner_radius_override_m between 50 and 2400)
);

create index if not exists planner_hubs_geo_gix
  on public.planner_hubs using gist (geo);

create index if not exists planner_hubs_lookup_idx
  on public.planner_hubs (activo, priority, hub_type);

create table if not exists public.planner_hub_stops (
  id bigint generated by default as identity primary key,
  hub_id bigint not null references public.planner_hubs(id) on delete cascade,
  parada_id bigint not null references public.paradas(id) on delete cascade,
  role text not null default 'both',
  priority integer not null default 100,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_hub_stops_role_chk
    check (role in ('arrival', 'departure', 'both')),
  constraint planner_hub_stops_priority_chk
    check (priority >= 0),
  constraint planner_hub_stops_hub_stop_role_uidx
    unique (hub_id, parada_id, role)
);

create index if not exists planner_hub_stops_hub_idx
  on public.planner_hub_stops (hub_id, role, activo, priority);

create index if not exists planner_hub_stops_parada_idx
  on public.planner_hub_stops (parada_id, activo);

drop trigger if exists set_updated_at_planner_hubs on public.planner_hubs;
create trigger set_updated_at_planner_hubs
before update on public.planner_hubs
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_planner_hub_stops on public.planner_hub_stops;
create trigger set_updated_at_planner_hub_stops
before update on public.planner_hub_stops
for each row execute function public.set_updated_at();

alter table public.planner_hubs enable row level security;
alter table public.planner_hub_stops enable row level security;

grant select on public.planner_hubs to anon, authenticated;
grant select on public.planner_hub_stops to anon, authenticated;

drop policy if exists planner_hubs_read_public on public.planner_hubs;
create policy planner_hubs_read_public
on public.planner_hubs
for select
to anon, authenticated
using (true);

drop policy if exists planner_hub_stops_read_public on public.planner_hub_stops;
create policy planner_hub_stops_read_public
on public.planner_hub_stops
for select
to anon, authenticated
using (true);

create or replace function public.planner_resolve_location_context(
  p_lat double precision,
  p_lng double precision
)
returns table (
  hub_key text,
  hub_name text,
  hub_type text,
  resolved_lat double precision,
  resolved_lng double precision,
  radius_m integer,
  planner_radius_override_m integer,
  arrival_stop_ids bigint[],
  departure_stop_ids bigint[]
)
language sql
stable
set search_path = public, extensions
as $$
with point as (
  select st_setsrid(st_makepoint(p_lng, p_lat), 4326)::geography as g
),
matching_hub as (
  select
    h.id,
    h.hub_key,
    h.hub_name,
    h.hub_type,
    h.lat,
    h.lng,
    h.radius_m,
    h.planner_radius_override_m,
    st_distance(h.geo, p.g)::integer as distance_m
  from point p
  join public.planner_hubs h
    on h.activo = true
   and st_dwithin(h.geo, p.g, h.radius_m)
  order by h.priority asc, distance_m asc, h.id asc
  limit 1
)
select
  h.hub_key,
  h.hub_name,
  h.hub_type,
  h.lat::double precision as resolved_lat,
  h.lng::double precision as resolved_lng,
  h.radius_m,
  h.planner_radius_override_m,
  (
    select coalesce(array_agg(phs.parada_id order by phs.priority asc, phs.parada_id asc), '{}')
    from public.planner_hub_stops phs
    where phs.hub_id = h.id
      and phs.activo = true
      and phs.role in ('arrival', 'both')
  ) as arrival_stop_ids,
  (
    select coalesce(array_agg(phs.parada_id order by phs.priority asc, phs.parada_id asc), '{}')
    from public.planner_hub_stops phs
    where phs.hub_id = h.id
      and phs.activo = true
      and phs.role in ('departure', 'both')
  ) as departure_stop_ids
from matching_hub h;
$$;

grant execute on function public.planner_resolve_location_context(double precision, double precision)
to anon, authenticated;

comment on table public.planner_hubs is
  'Hubs y landmarks operativos para ayudar al planner a resolver destinos ambiguos del centro de una ciudad.';

comment on table public.planner_hub_stops is
  'Paradas ancla por hub, separando roles de llegada y salida cuando haga falta.';

comment on function public.planner_resolve_location_context(double precision, double precision) is
  'Si una coordenada cae dentro de un hub/landmark conocido, devuelve el centro operativo del hub y sus paradas ancla.';
