set search_path = public, extensions;

-- Append-only runtime bindings for official CTP variants promoted into the
-- modern planner. This avoids rewriting ctp_preview_route_variant_map() every
-- time a new corridor is seeded.

create table if not exists public.planner_ctp_preview_route_bindings (
  id bigint generated by default as identity primary key,
  ruta_id integer not null references public.rutas(id) on delete cascade,
  route_code text not null,
  variant_family_code text,
  variant_code text,
  preview_scope text not null default 'route_stops'
    check (preview_scope in ('route_stops', 'nearby_stops')),
  preview_priority integer not null default 10
    check (preview_priority >= 0),
  reverse_stop_order boolean not null default false,
  activo boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now())
);

create unique index if not exists planner_ctp_preview_bindings_unique_idx
  on public.planner_ctp_preview_route_bindings (
    ruta_id,
    coalesce(variant_code, '__family__'),
    preview_scope
  );

alter table public.planner_ctp_preview_route_bindings enable row level security;

do $do$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'planner_ctp_preview_route_bindings'
      and policyname = 'planner_ctp_preview_route_bindings_select_active'
  ) then
    create policy planner_ctp_preview_route_bindings_select_active
      on public.planner_ctp_preview_route_bindings
      for select
      to anon, authenticated
      using (activo = true);
  end if;
end $do$;

grant select on public.planner_ctp_preview_route_bindings to anon, authenticated;

do $do$
declare
  function_sql text;
begin
  select pg_get_functiondef(p.oid)
  into function_sql
  from pg_proc p
  join pg_namespace n
    on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname = 'ctp_preview_route_variant_map';

  if function_sql is null then
    raise exception 'public.ctp_preview_route_variant_map() is required before installing runtime bindings';
  end if;

  if function_sql not like '%planner_ctp_preview_route_bindings%' then
    function_sql := replace(
      function_sql,
      $needle$  ) as v(ruta_id, route_code, variant_family_code, variant_code, preview_scope, preview_priority, reverse_stop_order);$needle$,
      $replacement$  ) as v(ruta_id, route_code, variant_family_code, variant_code, preview_scope, preview_priority, reverse_stop_order)
  union all
  select
    b.ruta_id,
    b.route_code,
    b.variant_family_code,
    b.variant_code,
    b.preview_scope,
    b.preview_priority,
    b.reverse_stop_order
  from public.planner_ctp_preview_route_bindings b
  where b.activo = true;$replacement$
    );

    execute function_sql;
  end if;
end $do$;

comment on table public.planner_ctp_preview_route_bindings is
  'Runtime CTP variant bindings appended to ctp_preview_route_variant_map for promoted corridors.';
