set search_path = public, extensions;

create extension if not exists btree_gist with schema extensions;

-- Fase 1 GTFS-like:
-- 1. planner_stop_areas: clusters macro/micro sobre paradas oficiales
-- 2. planner_boarding_points: puntos concretos de abordaje derivados de micro-clusters
-- 3. planner_transfer_edges: transferencias caminables explicitas entre boarding points

-- SECTION: TABLES

create table if not exists public.planner_stop_areas (
  id bigint generated by default as identity primary key,
  area_key text not null unique,
  parent_area_id bigint references public.planner_stop_areas(id) on delete cascade,
  cluster_level text not null,
  area_name text not null,
  lat double precision not null,
  lng double precision not null,
  geo geography(Point, 4326) generated always as (
    st_setsrid(st_makepoint(lng, lat), 4326)::geography
  ) stored,
  radius_m integer not null default 0,
  stop_count integer not null default 0,
  route_count integer not null default 0,
  family_count integer not null default 0,
  shared_corridor_stop_count integer not null default 0,
  dominant_name_share numeric(5,4) not null default 0,
  activo boolean not null default true,
  source text not null default 'auto_cluster',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_stop_areas_cluster_level_chk
    check (cluster_level in ('macro', 'micro')),
  constraint planner_stop_areas_radius_chk
    check (radius_m between 0 and 2500),
  constraint planner_stop_areas_stop_count_chk
    check (stop_count >= 0),
  constraint planner_stop_areas_route_count_chk
    check (route_count >= 0),
  constraint planner_stop_areas_family_count_chk
    check (family_count >= 0),
  constraint planner_stop_areas_shared_corridor_chk
    check (shared_corridor_stop_count >= 0),
  constraint planner_stop_areas_dominant_name_share_chk
    check (dominant_name_share between 0 and 1),
  constraint planner_stop_areas_source_chk
    check (source in ('auto_cluster', 'manual', 'ai_split', 'promoted_hub_bridge'))
);

create index if not exists planner_stop_areas_parent_idx
  on public.planner_stop_areas (parent_area_id);

create index if not exists planner_stop_areas_lookup_idx
  on public.planner_stop_areas (cluster_level, activo, family_count desc, route_count desc);

create index if not exists planner_stop_areas_geo_gix
  on public.planner_stop_areas using gist (geo);

create table if not exists public.planner_stop_area_members (
  id bigint generated by default as identity primary key,
  area_id bigint not null references public.planner_stop_areas(id) on delete cascade,
  stop_source_id bigint not null references public.staging_ctp_official_stops(source_id) on delete cascade,
  member_rank integer not null default 1,
  distance_to_centroid_m integer not null default 0,
  route_count integer not null default 0,
  family_count integer not null default 0,
  shared_corridor boolean not null default false,
  manual_review_required boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_stop_area_members_uidx unique (area_id, stop_source_id),
  constraint planner_stop_area_members_rank_chk check (member_rank >= 1),
  constraint planner_stop_area_members_distance_chk check (distance_to_centroid_m >= 0),
  constraint planner_stop_area_members_route_count_chk check (route_count >= 0),
  constraint planner_stop_area_members_family_count_chk check (family_count >= 0)
);

create index if not exists planner_stop_area_members_area_idx
  on public.planner_stop_area_members (area_id, member_rank);

create index if not exists planner_stop_area_members_stop_idx
  on public.planner_stop_area_members (stop_source_id);

create table if not exists public.planner_boarding_points (
  id bigint generated by default as identity primary key,
  boarding_key text not null unique,
  area_id bigint not null references public.planner_stop_areas(id) on delete cascade,
  parent_area_id bigint references public.planner_stop_areas(id) on delete set null,
  dominant_stop_source_id bigint references public.staging_ctp_official_stops(source_id) on delete set null,
  linked_parada_id bigint references public.paradas(id) on delete set null,
  boarding_name text not null,
  lat double precision not null,
  lng double precision not null,
  geo geography(Point, 4326) generated always as (
    st_setsrid(st_makepoint(lng, lat), 4326)::geography
  ) stored,
  stop_count integer not null default 0,
  route_count integer not null default 0,
  family_count integer not null default 0,
  activo boolean not null default true,
  source text not null default 'auto_micro_cluster',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_boarding_points_stop_count_chk check (stop_count >= 0),
  constraint planner_boarding_points_route_count_chk check (route_count >= 0),
  constraint planner_boarding_points_family_count_chk check (family_count >= 0),
  constraint planner_boarding_points_source_chk
    check (source in ('auto_micro_cluster', 'manual', 'importacion'))
);

create index if not exists planner_boarding_points_area_idx
  on public.planner_boarding_points (area_id);

create index if not exists planner_boarding_points_parent_idx
  on public.planner_boarding_points (parent_area_id);

create index if not exists planner_boarding_points_geo_gix
  on public.planner_boarding_points using gist (geo);

create index if not exists planner_boarding_points_parada_idx
  on public.planner_boarding_points (linked_parada_id);

create table if not exists public.planner_transfer_edges (
  id bigint generated by default as identity primary key,
  from_boarding_point_id bigint not null references public.planner_boarding_points(id) on delete cascade,
  to_boarding_point_id bigint not null references public.planner_boarding_points(id) on delete cascade,
  from_area_id bigint not null references public.planner_stop_areas(id) on delete cascade,
  to_area_id bigint not null references public.planner_stop_areas(id) on delete cascade,
  transfer_type text not null,
  distance_m integer not null,
  walk_time_min integer generated always as (
    greatest(1, ceil(distance_m::numeric / 80.0)::integer)
  ) stored,
  confidence numeric(5,4) not null default 0.5,
  activo boolean not null default true,
  source text not null default 'auto_walk',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint planner_transfer_edges_uidx unique (from_boarding_point_id, to_boarding_point_id),
  constraint planner_transfer_edges_not_self_chk
    check (from_boarding_point_id <> to_boarding_point_id),
  constraint planner_transfer_edges_distance_chk
    check (distance_m >= 0),
  constraint planner_transfer_edges_confidence_chk
    check (confidence between 0 and 1),
  constraint planner_transfer_edges_type_chk
    check (transfer_type in ('same_macro', 'nearby_walk', 'hub_walk', 'manual', 'prohibited')),
  constraint planner_transfer_edges_source_chk
    check (source in ('auto_walk', 'manual', 'hub_rule'))
);

create index if not exists planner_transfer_edges_from_idx
  on public.planner_transfer_edges (from_boarding_point_id, activo, transfer_type);

create index if not exists planner_transfer_edges_to_idx
  on public.planner_transfer_edges (to_boarding_point_id, activo, transfer_type);

drop trigger if exists set_updated_at_planner_stop_areas on public.planner_stop_areas;
create trigger set_updated_at_planner_stop_areas
before update on public.planner_stop_areas
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_planner_stop_area_members on public.planner_stop_area_members;
create trigger set_updated_at_planner_stop_area_members
before update on public.planner_stop_area_members
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_planner_boarding_points on public.planner_boarding_points;
create trigger set_updated_at_planner_boarding_points
before update on public.planner_boarding_points
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_planner_transfer_edges on public.planner_transfer_edges;
create trigger set_updated_at_planner_transfer_edges
before update on public.planner_transfer_edges
for each row execute function public.set_updated_at();

alter table public.planner_stop_areas enable row level security;
alter table public.planner_stop_area_members enable row level security;
alter table public.planner_boarding_points enable row level security;
alter table public.planner_transfer_edges enable row level security;

grant select on public.planner_stop_areas to anon, authenticated;
grant select on public.planner_stop_area_members to anon, authenticated;
grant select on public.planner_boarding_points to anon, authenticated;
grant select on public.planner_transfer_edges to anon, authenticated;

drop policy if exists planner_stop_areas_read_public on public.planner_stop_areas;
create policy planner_stop_areas_read_public
on public.planner_stop_areas
for select
to anon, authenticated
using (true);

drop policy if exists planner_stop_area_members_read_public on public.planner_stop_area_members;
create policy planner_stop_area_members_read_public
on public.planner_stop_area_members
for select
to anon, authenticated
using (true);

drop policy if exists planner_boarding_points_read_public on public.planner_boarding_points;
create policy planner_boarding_points_read_public
on public.planner_boarding_points
for select
to anon, authenticated
using (true);

drop policy if exists planner_transfer_edges_read_public on public.planner_transfer_edges;
create policy planner_transfer_edges_read_public
on public.planner_transfer_edges
for select
to anon, authenticated
using (true);

-- SECTION: REFRESH_STOP_AREAS

create or replace function public.planner_refresh_stop_areas(
  p_macro_cluster_m integer default 120,
  p_micro_cluster_m integer default 35,
  p_min_macro_stop_count integer default 2,
  p_min_family_count integer default 1
)
returns table (
  macro_area_count integer,
  micro_area_count integer,
  member_count integer
)
language plpgsql
set search_path = public, extensions
as $$
begin
  if p_macro_cluster_m < 25 or p_macro_cluster_m > 500 then
    raise exception 'p_macro_cluster_m fuera de rango: %', p_macro_cluster_m;
  end if;

  if p_micro_cluster_m < 5 or p_micro_cluster_m > p_macro_cluster_m then
    raise exception 'p_micro_cluster_m fuera de rango: %', p_micro_cluster_m;
  end if;

  if p_min_macro_stop_count < 1 or p_min_macro_stop_count > 10 then
    raise exception 'p_min_macro_stop_count fuera de rango: %', p_min_macro_stop_count;
  end if;

  if p_min_family_count < 1 or p_min_family_count > 25 then
    raise exception 'p_min_family_count fuera de rango: %', p_min_family_count;
  end if;

  create temp table tmp_planner_cluster_source on commit drop as
  with inferred_stats as (
    select
      s.source_id as stop_source_id,
      s.source_identifier,
      coalesce(nullif(trim(s.description_normalized), ''), nullif(trim(s.description_raw), ''), 'Parada oficial CTP') as stop_name,
      s.lat,
      s.lng,
      s.geom,
      count(distinct i.route_code_normalized) as route_count,
      count(distinct coalesce(nullif(i.variant_family_code, ''), i.route_code_normalized)) as family_count,
      bool_or(coalesce(i.shared_corridor, false)) as shared_corridor,
      bool_or(coalesce(i.manual_review_required, false)) as manual_review_required
    from public.staging_ctp_official_stops s
    join public.staging_ctp_route_stops_inferred i
      on i.stop_source_id = s.source_id
    group by
      s.source_id,
      s.source_identifier,
      s.description_normalized,
      s.description_raw,
      s.lat,
      s.lng,
      s.geom
  ),
  macro_seed as (
    select
      i.*,
      st_clusterdbscan(st_transform(i.geom, 3857), eps := p_macro_cluster_m, minpoints := greatest(1, p_min_macro_stop_count)) over () as macro_cluster_id
    from inferred_stats i
  )
  select
    m.*,
    coalesce('cluster_' || m.macro_cluster_id::text, 'noise_' || m.stop_source_id::text) as macro_group_key
  from macro_seed m;

  create index tmp_planner_cluster_source_macro_idx
    on tmp_planner_cluster_source (macro_group_key);

  create index tmp_planner_cluster_source_stop_idx
    on tmp_planner_cluster_source (stop_source_id);

  create temp table tmp_planner_macro_data on commit drop as
  with base as (
    select
      s.macro_group_key,
      avg(s.lat) as lat,
      avg(s.lng) as lng,
      count(*) as stop_count,
      sum(case when s.shared_corridor then 1 else 0 end) as shared_corridor_stop_count,
      array_agg(s.stop_source_id order by s.stop_source_id) as stop_ids
    from tmp_planner_cluster_source s
    group by s.macro_group_key
  ),
  route_stats as (
    select
      s.macro_group_key,
      count(distinct i.route_code_normalized) as route_count,
      count(distinct coalesce(nullif(i.variant_family_code, ''), i.route_code_normalized)) as family_count
    from tmp_planner_cluster_source s
    join public.staging_ctp_route_stops_inferred i
      on i.stop_source_id = s.stop_source_id
    group by s.macro_group_key
  ),
  name_stats as (
    select
      s.macro_group_key,
      s.stop_name,
      count(*) as name_count
    from tmp_planner_cluster_source s
    group by s.macro_group_key, s.stop_name
  ),
  name_pick as (
    select
      n.macro_group_key,
      n.stop_name as area_name,
      (n.name_count::numeric / nullif(sum(n.name_count) over (partition by n.macro_group_key), 0)::numeric)::numeric(5,4) as dominant_name_share,
      row_number() over (partition by n.macro_group_key order by n.name_count desc, n.stop_name asc) as rn
    from name_stats n
  ),
  radius_stats as (
    select
      b.macro_group_key,
      max(
        st_distance(
          st_setsrid(st_makepoint(s.lng, s.lat), 4326)::geography,
          st_setsrid(st_makepoint(b.lng, b.lat), 4326)::geography
        )
      )::integer as radius_m
    from base b
    join tmp_planner_cluster_source s
      on s.macro_group_key = b.macro_group_key
    group by b.macro_group_key
  )
  select
    'macro_' || md5(array_to_string(b.stop_ids, ',')) as area_key,
    b.macro_group_key,
    coalesce(np.area_name, 'Hub CTP') as area_name,
    b.lat,
    b.lng,
    coalesce(r.radius_m, 0) as radius_m,
    b.stop_count,
    coalesce(rs.route_count, 0) as route_count,
    coalesce(rs.family_count, 0) as family_count,
    b.shared_corridor_stop_count,
    coalesce(np.dominant_name_share, 0)::numeric(5,4) as dominant_name_share,
    b.stop_ids
  from base b
  left join route_stats rs
    on rs.macro_group_key = b.macro_group_key
  left join radius_stats r
    on r.macro_group_key = b.macro_group_key
  left join name_pick np
    on np.macro_group_key = b.macro_group_key
   and np.rn = 1
  where (b.stop_count >= p_min_macro_stop_count or b.stop_count = 1)
    and coalesce(rs.family_count, 0) >= p_min_family_count;

  delete from public.planner_stop_areas
  where source = 'auto_cluster';

  insert into public.planner_stop_areas (
    area_key,
    parent_area_id,
    cluster_level,
    area_name,
    lat,
    lng,
    radius_m,
    stop_count,
    route_count,
    family_count,
    shared_corridor_stop_count,
    dominant_name_share,
    activo,
    source,
    metadata
  )
  select
    m.area_key,
    null,
    'macro',
    m.area_name,
    m.lat,
    m.lng,
    m.radius_m,
    m.stop_count,
    m.route_count,
    m.family_count,
    m.shared_corridor_stop_count,
    m.dominant_name_share,
    true,
    'auto_cluster',
    jsonb_build_object(
      'macro_group_key', m.macro_group_key,
      'refresh_params', jsonb_build_object(
        'macro_cluster_m', p_macro_cluster_m,
        'micro_cluster_m', p_micro_cluster_m,
        'min_macro_stop_count', p_min_macro_stop_count,
        'min_family_count', p_min_family_count
      )
    )
  from tmp_planner_macro_data m;

  create temp table tmp_planner_macro_area_map on commit drop as
  select
    a.id as area_id,
    (a.metadata ->> 'macro_group_key') as macro_group_key
  from public.planner_stop_areas a
  where a.source = 'auto_cluster'
    and a.cluster_level = 'macro';

  create temp table tmp_planner_micro_source on commit drop as
  with micro_seed as (
    select
      s.*,
      st_clusterdbscan(st_transform(s.geom, 3857), eps := p_micro_cluster_m, minpoints := 1) over (partition by s.macro_group_key) as micro_cluster_id
    from tmp_planner_cluster_source s
    join tmp_planner_macro_data m
      on m.macro_group_key = s.macro_group_key
  )
  select
    ms.*,
    ms.macro_group_key || '_micro_' || coalesce(ms.micro_cluster_id::text, '0') as micro_group_key
  from micro_seed ms;

  create index tmp_planner_micro_source_micro_idx
    on tmp_planner_micro_source (micro_group_key);

  create index tmp_planner_micro_source_stop_idx
    on tmp_planner_micro_source (stop_source_id);

  create temp table tmp_planner_micro_data on commit drop as
  with base as (
    select
      s.macro_group_key,
      s.micro_group_key,
      avg(s.lat) as lat,
      avg(s.lng) as lng,
      count(*) as stop_count,
      sum(case when s.shared_corridor then 1 else 0 end) as shared_corridor_stop_count,
      array_agg(s.stop_source_id order by s.stop_source_id) as stop_ids
    from tmp_planner_micro_source s
    group by s.macro_group_key, s.micro_group_key
  ),
  route_stats as (
    select
      s.micro_group_key,
      count(distinct i.route_code_normalized) as route_count,
      count(distinct coalesce(nullif(i.variant_family_code, ''), i.route_code_normalized)) as family_count
    from tmp_planner_micro_source s
    join public.staging_ctp_route_stops_inferred i
      on i.stop_source_id = s.stop_source_id
    group by s.micro_group_key
  ),
  name_stats as (
    select
      s.micro_group_key,
      s.stop_name,
      count(*) as name_count
    from tmp_planner_micro_source s
    group by s.micro_group_key, s.stop_name
  ),
  name_pick as (
    select
      n.micro_group_key,
      n.stop_name as area_name,
      (n.name_count::numeric / nullif(sum(n.name_count) over (partition by n.micro_group_key), 0)::numeric)::numeric(5,4) as dominant_name_share,
      row_number() over (partition by n.micro_group_key order by n.name_count desc, n.stop_name asc) as rn
    from name_stats n
  ),
  radius_stats as (
    select
      b.micro_group_key,
      max(
        st_distance(
          st_setsrid(st_makepoint(s.lng, s.lat), 4326)::geography,
          st_setsrid(st_makepoint(b.lng, b.lat), 4326)::geography
        )
      )::integer as radius_m
    from base b
    join tmp_planner_micro_source s
      on s.micro_group_key = b.micro_group_key
    group by b.micro_group_key
  )
  select
    'micro_' || md5(array_to_string(b.stop_ids, ',')) as area_key,
    b.macro_group_key,
    b.micro_group_key,
    coalesce(np.area_name, 'Plataforma CTP') as area_name,
    b.lat,
    b.lng,
    coalesce(r.radius_m, 0) as radius_m,
    b.stop_count,
    coalesce(rs.route_count, 0) as route_count,
    coalesce(rs.family_count, 0) as family_count,
    b.shared_corridor_stop_count,
    coalesce(np.dominant_name_share, 0)::numeric(5,4) as dominant_name_share,
    b.stop_ids
  from base b
  left join route_stats rs
    on rs.micro_group_key = b.micro_group_key
  left join radius_stats r
    on r.micro_group_key = b.micro_group_key
  left join name_pick np
    on np.micro_group_key = b.micro_group_key
   and np.rn = 1;

  insert into public.planner_stop_areas (
    area_key,
    parent_area_id,
    cluster_level,
    area_name,
    lat,
    lng,
    radius_m,
    stop_count,
    route_count,
    family_count,
    shared_corridor_stop_count,
    dominant_name_share,
    activo,
    source,
    metadata
  )
  select
    m.area_key,
    parent_map.area_id,
    'micro',
    m.area_name,
    m.lat,
    m.lng,
    m.radius_m,
    m.stop_count,
    m.route_count,
    m.family_count,
    m.shared_corridor_stop_count,
    m.dominant_name_share,
    true,
    'auto_cluster',
    jsonb_build_object(
      'macro_group_key', m.macro_group_key,
      'micro_group_key', m.micro_group_key
    )
  from tmp_planner_micro_data m
  join tmp_planner_macro_area_map parent_map
    on parent_map.macro_group_key = m.macro_group_key;

  create temp table tmp_planner_area_map on commit drop as
  select
    a.id as area_id,
    a.cluster_level,
    (a.metadata ->> 'macro_group_key') as macro_group_key,
    (a.metadata ->> 'micro_group_key') as micro_group_key,
    a.lat,
    a.lng
  from public.planner_stop_areas a
  where a.source = 'auto_cluster';

  insert into public.planner_stop_area_members (
    area_id,
    stop_source_id,
    member_rank,
    distance_to_centroid_m,
    route_count,
    family_count,
    shared_corridor,
    manual_review_required,
    metadata
  )
  with area_members as (
    select
      map.area_id,
      map.cluster_level,
      s.stop_source_id,
      s.source_identifier,
      s.route_count,
      s.family_count,
      s.shared_corridor,
      s.manual_review_required,
      st_distance(
        st_setsrid(st_makepoint(s.lng, s.lat), 4326)::geography,
        st_setsrid(st_makepoint(map.lng, map.lat), 4326)::geography
      )::integer as distance_to_centroid_m
    from tmp_planner_area_map map
    join tmp_planner_cluster_source s
      on map.cluster_level = 'macro'
     and map.macro_group_key = s.macro_group_key

    union all

    select
      map.area_id,
      map.cluster_level,
      s.stop_source_id,
      s.source_identifier,
      s.route_count,
      s.family_count,
      s.shared_corridor,
      s.manual_review_required,
      st_distance(
        st_setsrid(st_makepoint(s.lng, s.lat), 4326)::geography,
        st_setsrid(st_makepoint(map.lng, map.lat), 4326)::geography
      )::integer as distance_to_centroid_m
    from tmp_planner_area_map map
    join tmp_planner_micro_source s
      on map.cluster_level = 'micro'
     and map.micro_group_key = s.micro_group_key
  ),
  ranked as (
    select
      am.*,
      row_number() over (
        partition by am.area_id
        order by
          am.distance_to_centroid_m asc,
          am.family_count desc,
          am.route_count desc,
          am.stop_source_id asc
      ) as member_rank
    from area_members am
  )
  select
    ranked.area_id,
    ranked.stop_source_id,
    ranked.member_rank,
    ranked.distance_to_centroid_m,
    ranked.route_count,
    ranked.family_count,
    ranked.shared_corridor,
    ranked.manual_review_required,
    jsonb_build_object(
      'cluster_level', ranked.cluster_level,
      'source_identifier', ranked.source_identifier
    )
  from ranked;

  return query
  select
    (select count(*)::integer from public.planner_stop_areas where source = 'auto_cluster' and cluster_level = 'macro'),
    (select count(*)::integer from public.planner_stop_areas where source = 'auto_cluster' and cluster_level = 'micro'),
    (select count(*)::integer from public.planner_stop_area_members m join public.planner_stop_areas a on a.id = m.area_id where a.source = 'auto_cluster');
end;
$$;

-- SECTION: REFRESH_BOARDING_POINTS

create or replace function public.planner_refresh_boarding_points(
  p_link_parada_m integer default 90
)
returns table (
  boarding_point_count integer,
  linked_parada_count integer
)
language plpgsql
set search_path = public, extensions
as $$
begin
  if p_link_parada_m < 10 or p_link_parada_m > 500 then
    raise exception 'p_link_parada_m fuera de rango: %', p_link_parada_m;
  end if;

  delete from public.planner_boarding_points
  where source = 'auto_micro_cluster';

  insert into public.planner_boarding_points (
    boarding_key,
    area_id,
    parent_area_id,
    dominant_stop_source_id,
    linked_parada_id,
    boarding_name,
    lat,
    lng,
    stop_count,
    route_count,
    family_count,
    activo,
    source,
    metadata
  )
  select
    replace(a.area_key, 'micro_', 'bp_') as boarding_key,
    a.id as area_id,
    a.parent_area_id,
    dominant_member.stop_source_id as dominant_stop_source_id,
    nearest_parada.parada_id as linked_parada_id,
    coalesce(
      nullif(trim(dominant_stop.description_normalized), ''),
      nullif(trim(dominant_stop.description_raw), ''),
      a.area_name
    ) as boarding_name,
    a.lat,
    a.lng,
    a.stop_count,
    a.route_count,
    a.family_count,
    true,
    'auto_micro_cluster',
    jsonb_build_object(
      'cluster_level', a.cluster_level,
      'linked_parada_distance_m', nearest_parada.distance_m,
      'dominant_name_share', a.dominant_name_share
    )
  from public.planner_stop_areas a
  left join lateral (
    select
      m.stop_source_id
    from public.planner_stop_area_members m
    where m.area_id = a.id
    order by m.member_rank asc, m.stop_source_id asc
    limit 1
  ) dominant_member on true
  left join public.staging_ctp_official_stops dominant_stop
    on dominant_stop.source_id = dominant_member.stop_source_id
  left join lateral (
    select
      p.id as parada_id,
      st_distance(
        p.geo,
        st_setsrid(st_makepoint(a.lng, a.lat), 4326)::geography
      )::integer as distance_m
    from public.paradas p
    where p.activo = true
      and st_dwithin(
        p.geo,
        st_setsrid(st_makepoint(a.lng, a.lat), 4326)::geography,
        p_link_parada_m
      )
    order by distance_m asc, p.id asc
    limit 1
  ) nearest_parada on true
  where a.source = 'auto_cluster'
    and a.cluster_level = 'micro'
    and a.activo = true;

  return query
  select
    (select count(*)::integer from public.planner_boarding_points where source = 'auto_micro_cluster'),
    (select count(*)::integer from public.planner_boarding_points where source = 'auto_micro_cluster' and linked_parada_id is not null);
end;
$$;

-- SECTION: REFRESH_TRANSFER_EDGES

create or replace function public.planner_refresh_transfer_edges(
  p_same_macro_transfer_m integer default 160,
  p_nearby_transfer_m integer default 220
)
returns table (
  transfer_edge_count integer,
  same_macro_edge_count integer,
  nearby_walk_edge_count integer
)
language plpgsql
set search_path = public, extensions
as $$
begin
  if p_same_macro_transfer_m < 20 or p_same_macro_transfer_m > 500 then
    raise exception 'p_same_macro_transfer_m fuera de rango: %', p_same_macro_transfer_m;
  end if;

  if p_nearby_transfer_m < p_same_macro_transfer_m or p_nearby_transfer_m > 800 then
    raise exception 'p_nearby_transfer_m fuera de rango: %', p_nearby_transfer_m;
  end if;

  delete from public.planner_transfer_edges
  where source = 'auto_walk';

  insert into public.planner_transfer_edges (
    from_boarding_point_id,
    to_boarding_point_id,
    from_area_id,
    to_area_id,
    transfer_type,
    distance_m,
    confidence,
    activo,
    source,
    metadata
  )
  with candidate_edges as (
    select
      bf.id as from_boarding_point_id,
      bt.id as to_boarding_point_id,
      bf.area_id as from_area_id,
      bt.area_id as to_area_id,
      bf.parent_area_id as from_parent_area_id,
      bt.parent_area_id as to_parent_area_id,
      bf.linked_parada_id as from_linked_parada_id,
      bt.linked_parada_id as to_linked_parada_id,
      st_distance(bf.geo, bt.geo)::integer as distance_m
    from public.planner_boarding_points bf
    join public.planner_boarding_points bt
      on bf.id <> bt.id
     and bf.area_id <> bt.area_id
     and bf.source = 'auto_micro_cluster'
     and bt.source = 'auto_micro_cluster'
     and bf.activo = true
     and bt.activo = true
     and st_dwithin(bf.geo, bt.geo, p_nearby_transfer_m)
  )
  select
    c.from_boarding_point_id,
    c.to_boarding_point_id,
    c.from_area_id,
    c.to_area_id,
    case
      when c.from_parent_area_id is not null
       and c.from_parent_area_id = c.to_parent_area_id
       and c.distance_m <= p_same_macro_transfer_m
          then 'same_macro'
      when c.distance_m <= p_nearby_transfer_m
          then 'nearby_walk'
      else null
    end as transfer_type,
    c.distance_m,
    case
      when c.from_parent_area_id is not null
       and c.from_parent_area_id = c.to_parent_area_id
       and c.distance_m <= p_same_macro_transfer_m
        then greatest(0.80, (1 - (c.distance_m::numeric / greatest(p_same_macro_transfer_m, 1)::numeric) * 0.20)::numeric)
      else greatest(0.35, (1 - (c.distance_m::numeric / greatest(p_nearby_transfer_m, 1)::numeric) * 0.65)::numeric)
    end::numeric(5,4) as confidence,
    true,
    'auto_walk',
    jsonb_build_object(
      'from_parent_area_id', c.from_parent_area_id,
      'to_parent_area_id', c.to_parent_area_id,
      'from_linked_parada_id', c.from_linked_parada_id,
      'to_linked_parada_id', c.to_linked_parada_id
    )
  from candidate_edges c
  where (
    c.from_parent_area_id is not null
    and c.from_parent_area_id = c.to_parent_area_id
    and c.distance_m <= p_same_macro_transfer_m
  ) or c.distance_m <= p_nearby_transfer_m
  on conflict on constraint planner_transfer_edges_uidx do update
  set
    from_area_id = excluded.from_area_id,
    to_area_id = excluded.to_area_id,
    transfer_type = excluded.transfer_type,
    distance_m = excluded.distance_m,
    confidence = excluded.confidence,
    activo = excluded.activo,
    source = excluded.source,
    metadata = excluded.metadata,
    updated_at = timezone('utc', now());

  return query
  select
    (select count(*)::integer from public.planner_transfer_edges where source = 'auto_walk'),
    (select count(*)::integer from public.planner_transfer_edges where source = 'auto_walk' and transfer_type = 'same_macro'),
    (select count(*)::integer from public.planner_transfer_edges where source = 'auto_walk' and transfer_type = 'nearby_walk');
end;
$$;

-- SECTION: ORCHESTRATOR_AND_QA

create or replace function public.planner_refresh_stop_network_phase1(
  p_macro_cluster_m integer default 120,
  p_micro_cluster_m integer default 35,
  p_min_macro_stop_count integer default 2,
  p_min_family_count integer default 1,
  p_link_parada_m integer default 90,
  p_same_macro_transfer_m integer default 160,
  p_nearby_transfer_m integer default 220
)
returns table (
  macro_area_count integer,
  micro_area_count integer,
  member_count integer,
  boarding_point_count integer,
  linked_parada_count integer,
  transfer_edge_count integer,
  same_macro_edge_count integer,
  nearby_walk_edge_count integer
)
language plpgsql
set search_path = public, extensions
as $$
declare
  v_stop_areas record;
  v_boarding record;
  v_edges record;
begin
  select * into v_stop_areas
  from public.planner_refresh_stop_areas(
    p_macro_cluster_m,
    p_micro_cluster_m,
    p_min_macro_stop_count,
    p_min_family_count
  );

  select * into v_boarding
  from public.planner_refresh_boarding_points(p_link_parada_m);

  select * into v_edges
  from public.planner_refresh_transfer_edges(
    p_same_macro_transfer_m,
    p_nearby_transfer_m
  );

  return query
  select
    v_stop_areas.macro_area_count,
    v_stop_areas.micro_area_count,
    v_stop_areas.member_count,
    v_boarding.boarding_point_count,
    v_boarding.linked_parada_count,
    v_edges.transfer_edge_count,
    v_edges.same_macro_edge_count,
    v_edges.nearby_walk_edge_count;
end;
$$;

create or replace view public.planner_stop_areas_qa as
select
  a.id,
  a.area_key,
  a.cluster_level,
  parent.area_key as parent_area_key,
  a.area_name,
  a.lat,
  a.lng,
  a.radius_m,
  a.stop_count,
  a.route_count,
  a.family_count,
  a.shared_corridor_stop_count,
  a.dominant_name_share,
  a.source,
  a.activo,
  a.metadata
from public.planner_stop_areas a
left join public.planner_stop_areas parent
  on parent.id = a.parent_area_id;

create or replace view public.planner_boarding_points_qa as
select
  b.id,
  b.boarding_key,
  b.boarding_name,
  b.area_id,
  a.area_key,
  a.area_name,
  b.parent_area_id,
  parent.area_key as parent_area_key,
  parent.area_name as parent_area_name,
  b.stop_count,
  b.route_count,
  b.family_count,
  b.linked_parada_id,
  p.nombre as linked_parada_nombre,
  coalesce((b.metadata ->> 'linked_parada_distance_m')::integer, null) as linked_parada_distance_m,
  b.source,
  b.activo,
  b.metadata
from public.planner_boarding_points b
join public.planner_stop_areas a
  on a.id = b.area_id
left join public.planner_stop_areas parent
  on parent.id = b.parent_area_id
left join public.paradas p
  on p.id = b.linked_parada_id;

create or replace view public.planner_transfer_edges_qa as
select
  e.id,
  e.transfer_type,
  e.distance_m,
  e.walk_time_min,
  e.confidence,
  e.from_boarding_point_id,
  from_bp.boarding_key as from_boarding_key,
  from_bp.boarding_name as from_boarding_name,
  e.to_boarding_point_id,
  to_bp.boarding_key as to_boarding_key,
  to_bp.boarding_name as to_boarding_name,
  e.from_area_id,
  from_area.area_key as from_area_key,
  e.to_area_id,
  to_area.area_key as to_area_key,
  e.source,
  e.activo,
  e.metadata
from public.planner_transfer_edges e
join public.planner_boarding_points from_bp
  on from_bp.id = e.from_boarding_point_id
join public.planner_boarding_points to_bp
  on to_bp.id = e.to_boarding_point_id
join public.planner_stop_areas from_area
  on from_area.id = e.from_area_id
join public.planner_stop_areas to_area
  on to_area.id = e.to_area_id;

grant select on public.planner_stop_areas_qa to anon, authenticated;
grant select on public.planner_boarding_points_qa to anon, authenticated;
grant select on public.planner_transfer_edges_qa to anon, authenticated;

grant execute on function public.planner_refresh_stop_areas(integer, integer, integer, integer)
  to service_role;
grant execute on function public.planner_refresh_boarding_points(integer)
  to service_role;
grant execute on function public.planner_refresh_transfer_edges(integer, integer)
  to service_role;
grant execute on function public.planner_refresh_stop_network_phase1(integer, integer, integer, integer, integer, integer, integer)
  to service_role;

comment on table public.planner_stop_areas is
  'Agrupa paradas oficiales CTP en areas macro y micro para modelar hubs y puntos de abordaje de forma GTFS-like.';

comment on table public.planner_stop_area_members is
  'Miembros oficiales de cada stop area, con ranking y distancia al centroide para QA y promotion.';

comment on table public.planner_boarding_points is
  'Puntos concretos de abordaje derivados de micro-clusters y enlazados cuando es posible a public.paradas.';

comment on table public.planner_transfer_edges is
  'Transferencias caminables explicitas entre boarding points para mejorar el ranking y evitar transbordos absurdos.';

comment on function public.planner_refresh_stop_network_phase1(integer, integer, integer, integer, integer, integer, integer) is
  'Refresca la Fase 1 GTFS-like: stop areas, boarding points y transfer edges.';
