set search_path = public, extensions;

create extension if not exists btree_gist with schema extensions;

create table if not exists public.route_patterns (
  id bigint generated by default as identity primary key,
  ruta_id bigint not null references public.rutas(id) on delete cascade,
  sentido text not null default 'ida',
  pattern_code text not null,
  nombre text,
  headsign text,
  stop_signature text not null,
  parada_inicial_id bigint references public.paradas(id) on delete set null,
  parada_final_id bigint references public.paradas(id) on delete set null,
  parada_count integer not null default 0,
  distancia_total_m integer,
  activo boolean not null default true,
  fuente text not null default 'importacion',
  categoria_operativa text not null default 'desconocida',
  clasificacion_fuente text not null default 'sin_clasificar',
  clasificacion_confianza numeric(4,3) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint route_patterns_ruta_sentido_code_uidx unique (ruta_id, sentido, pattern_code),
  constraint route_patterns_sentido_chk
    check (sentido in ('ida', 'vuelta', 'loop', 'ambos')),
  constraint route_patterns_parada_count_chk
    check (parada_count >= 0),
  constraint route_patterns_fuente_chk
    check (fuente in ('legacy_migration', 'manual', 'sistema', 'importacion', 'gtfs')),
  constraint route_patterns_categoria_operativa_chk
    check (categoria_operativa in ('local', 'interurbana', 'expreso', 'troncal', 'desconocida')),
  constraint route_patterns_clasificacion_fuente_chk
    check (clasificacion_fuente in ('sin_clasificar', 'inferencia_nombre', 'manual', 'aresep', 'sistema', 'importacion')),
  constraint route_patterns_clasificacion_confianza_chk
    check (clasificacion_confianza between 0 and 1)
);

create index if not exists route_patterns_ruta_sentido_idx
  on public.route_patterns (ruta_id, sentido)
  where activo = true;

create index if not exists route_patterns_stop_signature_idx
  on public.route_patterns (stop_signature);

create index if not exists route_patterns_categoria_operativa_idx
  on public.route_patterns (categoria_operativa)
  where activo = true;

create index if not exists route_patterns_clasificacion_fuente_idx
  on public.route_patterns (clasificacion_fuente);

create table if not exists public.route_pattern_stops (
  id bigint generated by default as identity primary key,
  pattern_id bigint not null references public.route_patterns(id) on delete cascade,
  parada_id bigint not null references public.paradas(id) on delete cascade,
  stop_sequence integer not null,
  es_subida boolean not null default true,
  es_bajada boolean not null default true,
  pickup_type smallint not null default 0,
  drop_off_type smallint not null default 0,
  distancia_acumulada_m integer,
  tiempo_estimado_desde_inicio_min integer,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint route_pattern_stops_pattern_sequence_uidx unique (pattern_id, stop_sequence),
  constraint route_pattern_stops_sequence_chk check (stop_sequence >= 0),
  constraint route_pattern_stops_pickup_chk check (pickup_type between 0 and 3),
  constraint route_pattern_stops_dropoff_chk check (drop_off_type between 0 and 3)
);

create index if not exists route_pattern_stops_pattern_idx
  on public.route_pattern_stops (pattern_id, stop_sequence);

create index if not exists route_pattern_stops_parada_idx
  on public.route_pattern_stops (parada_id);

create table if not exists public.service_windows (
  id bigint generated by default as identity primary key,
  pattern_id bigint not null references public.route_patterns(id) on delete cascade,
  dia_tipo text not null default 'habil',
  hora_inicio time not null,
  hora_fin time not null,
  frecuencia_promedio_min integer not null,
  espera_promedio_min integer generated always as (
    greatest(1, ceil(frecuencia_promedio_min::numeric / 2.0)::integer)
  ) stored,
  minuto_inicio integer generated always as (
    extract(hour from hora_inicio)::integer * 60
    + extract(minute from hora_inicio)::integer
  ) stored,
  minuto_fin integer generated always as (
    extract(hour from hora_fin)::integer * 60
    + extract(minute from hora_fin)::integer
  ) stored,
  activo boolean not null default true,
  source_ruta_frecuencia_id bigint,
  notas text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint service_windows_dia_tipo_chk
    check (dia_tipo in ('habil', 'sabado', 'domingo', 'feriado')),
  constraint service_windows_hora_rango_chk
    check (hora_fin > hora_inicio),
  constraint service_windows_frecuencia_chk
    check (frecuencia_promedio_min between 1 and 240)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_windows_no_overlap_excl'
      and conrelid = 'public.service_windows'::regclass
  ) then
    alter table public.service_windows
      add constraint service_windows_no_overlap_excl
      exclude using gist (
        pattern_id with =,
        dia_tipo with =,
        int4range(minuto_inicio, minuto_fin, '[)') with &&
      )
      where (activo);
  end if;
end $$;

create index if not exists service_windows_pattern_day_idx
  on public.service_windows (pattern_id, dia_tipo, hora_inicio, hora_fin)
  where activo = true;

create index if not exists service_windows_source_freq_idx
  on public.service_windows (source_ruta_frecuencia_id);

drop trigger if exists set_updated_at_route_patterns on public.route_patterns;
create trigger set_updated_at_route_patterns
before update on public.route_patterns
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_route_pattern_stops on public.route_pattern_stops;
create trigger set_updated_at_route_pattern_stops
before update on public.route_pattern_stops
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_service_windows on public.service_windows;
create trigger set_updated_at_service_windows
before update on public.service_windows
for each row execute function public.set_updated_at();

alter table public.route_patterns enable row level security;
alter table public.route_pattern_stops enable row level security;
alter table public.service_windows enable row level security;

grant select on public.route_patterns to anon, authenticated;
grant select on public.route_pattern_stops to anon, authenticated;
grant select on public.service_windows to anon, authenticated;

drop policy if exists route_patterns_read_public on public.route_patterns;
create policy route_patterns_read_public
on public.route_patterns
for select
to anon, authenticated
using (true);

drop policy if exists route_pattern_stops_read_public on public.route_pattern_stops;
create policy route_pattern_stops_read_public
on public.route_pattern_stops
for select
to anon, authenticated
using (true);

drop policy if exists service_windows_read_public on public.service_windows;
create policy service_windows_read_public
on public.service_windows
for select
to anon, authenticated
using (true);

comment on table public.route_patterns is
  'Runtime moderno de planner en Prueba: patrones operativos por ruta y sentido.';

comment on table public.route_pattern_stops is
  'Secuencia fija de paradas por patron del planner moderno en Prueba.';

comment on table public.service_windows is
  'Ventanas de servicio para estimar espera/frecuencia en el planner moderno de Prueba.';
