set search_path = public, extensions;

create extension if not exists btree_gist with schema extensions;

-- Fase 1 GTFS-like:
-- 1. route_patterns: una variante operativa por ruta y sentido
-- 2. route_pattern_stops: secuencia fija de paradas por variante
-- 3. service_windows: ventanas de servicio basadas en frecuencia por variante
--
-- Esta migracion no elimina ruta_paradas ni ruta_frecuencias.
-- Hace backfill desde ambas para no empezar de cero y permitir una adopcion gradual.

create table if not exists public.route_patterns (
  id bigint generated by default as identity primary key,
  ruta_id bigint not null references public.rutas(id) on delete cascade,
  sentido text not null default 'ida',
  pattern_code text not null,
  nombre text,
  headsign text,
  stop_signature text not null,
  parada_inicial_id bigint references public.paradas(id) on delete set null,
  parada_final_id bigint references public.paradas(id) on delete set null,
  parada_count integer not null default 0,
  distancia_total_m integer,
  activo boolean not null default true,
  fuente text not null default 'legacy_migration',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint route_patterns_ruta_sentido_code_uidx unique (ruta_id, sentido, pattern_code)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_patterns_sentido_chk'
      and conrelid = 'public.route_patterns'::regclass
  ) then
    alter table public.route_patterns
      add constraint route_patterns_sentido_chk
      check (sentido in ('ida', 'vuelta', 'loop', 'ambos'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_patterns_parada_count_chk'
      and conrelid = 'public.route_patterns'::regclass
  ) then
    alter table public.route_patterns
      add constraint route_patterns_parada_count_chk
      check (parada_count >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_patterns_fuente_chk'
      and conrelid = 'public.route_patterns'::regclass
  ) then
    alter table public.route_patterns
      add constraint route_patterns_fuente_chk
      check (fuente in ('legacy_migration', 'manual', 'sistema', 'importacion', 'gtfs'));
  end if;
end $$;

create index if not exists route_patterns_ruta_sentido_idx
  on public.route_patterns (ruta_id, sentido)
  where activo = true;

create index if not exists route_patterns_stop_signature_idx
  on public.route_patterns (stop_signature);

create table if not exists public.route_pattern_stops (
  id bigint generated by default as identity primary key,
  pattern_id bigint not null references public.route_patterns(id) on delete cascade,
  parada_id bigint not null references public.paradas(id) on delete cascade,
  stop_sequence integer not null,
  es_subida boolean not null default true,
  es_bajada boolean not null default true,
  pickup_type smallint not null default 0,
  drop_off_type smallint not null default 0,
  distancia_acumulada_m integer,
  tiempo_estimado_desde_inicio_min integer,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint route_pattern_stops_pattern_sequence_uidx unique (pattern_id, stop_sequence)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_pattern_stops_sequence_chk'
      and conrelid = 'public.route_pattern_stops'::regclass
  ) then
    alter table public.route_pattern_stops
      add constraint route_pattern_stops_sequence_chk
      check (stop_sequence >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_pattern_stops_pickup_chk'
      and conrelid = 'public.route_pattern_stops'::regclass
  ) then
    alter table public.route_pattern_stops
      add constraint route_pattern_stops_pickup_chk
      check (pickup_type between 0 and 3);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_pattern_stops_dropoff_chk'
      and conrelid = 'public.route_pattern_stops'::regclass
  ) then
    alter table public.route_pattern_stops
      add constraint route_pattern_stops_dropoff_chk
      check (drop_off_type between 0 and 3);
  end if;
end $$;

create index if not exists route_pattern_stops_pattern_idx
  on public.route_pattern_stops (pattern_id, stop_sequence);

create index if not exists route_pattern_stops_parada_idx
  on public.route_pattern_stops (parada_id);

create table if not exists public.service_windows (
  id bigint generated by default as identity primary key,
  pattern_id bigint not null references public.route_patterns(id) on delete cascade,
  dia_tipo text not null default 'habil',
  hora_inicio time not null,
  hora_fin time not null,
  frecuencia_promedio_min integer not null,
  espera_promedio_min integer generated always as (
    greatest(1, ceil(frecuencia_promedio_min::numeric / 2.0)::integer)
  ) stored,
  minuto_inicio integer generated always as (
    extract(hour from hora_inicio)::integer * 60
    + extract(minute from hora_inicio)::integer
  ) stored,
  minuto_fin integer generated always as (
    extract(hour from hora_fin)::integer * 60
    + extract(minute from hora_fin)::integer
  ) stored,
  activo boolean not null default true,
  source_ruta_frecuencia_id bigint references public.ruta_frecuencias(id) on delete set null,
  notas text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_windows_dia_tipo_chk'
      and conrelid = 'public.service_windows'::regclass
  ) then
    alter table public.service_windows
      add constraint service_windows_dia_tipo_chk
      check (dia_tipo in ('habil', 'sabado', 'domingo', 'feriado'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_windows_hora_rango_chk'
      and conrelid = 'public.service_windows'::regclass
  ) then
    alter table public.service_windows
      add constraint service_windows_hora_rango_chk
      check (hora_fin > hora_inicio);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_windows_frecuencia_chk'
      and conrelid = 'public.service_windows'::regclass
  ) then
    alter table public.service_windows
      add constraint service_windows_frecuencia_chk
      check (frecuencia_promedio_min between 1 and 240);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'service_windows_no_overlap_excl'
      and conrelid = 'public.service_windows'::regclass
  ) then
    alter table public.service_windows
      add constraint service_windows_no_overlap_excl
      exclude using gist (
        pattern_id with =,
        dia_tipo with =,
        int4range(minuto_inicio, minuto_fin, '[)') with &&
      )
      where (activo);
  end if;
end $$;

create index if not exists service_windows_pattern_day_idx
  on public.service_windows (pattern_id, dia_tipo, hora_inicio, hora_fin)
  where activo = true;

create index if not exists service_windows_source_freq_idx
  on public.service_windows (source_ruta_frecuencia_id)
  where source_ruta_frecuencia_id is not null;

drop trigger if exists set_updated_at_route_patterns on public.route_patterns;
create trigger set_updated_at_route_patterns
before update on public.route_patterns
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_route_pattern_stops on public.route_pattern_stops;
create trigger set_updated_at_route_pattern_stops
before update on public.route_pattern_stops
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_service_windows on public.service_windows;
create trigger set_updated_at_service_windows
before update on public.service_windows
for each row
execute function public.set_updated_at();

alter table public.route_patterns enable row level security;
alter table public.route_pattern_stops enable row level security;
alter table public.service_windows enable row level security;

drop policy if exists route_patterns_read_public on public.route_patterns;
create policy route_patterns_read_public
on public.route_patterns
for select
to anon, authenticated
using (true);

drop policy if exists route_pattern_stops_read_public on public.route_pattern_stops;
create policy route_pattern_stops_read_public
on public.route_pattern_stops
for select
to anon, authenticated
using (true);

drop policy if exists service_windows_read_public on public.service_windows;
create policy service_windows_read_public
on public.service_windows
for select
to anon, authenticated
using (true);

comment on table public.route_patterns is
  'Variantes operativas por ruta y sentido. Capa intermedia GTFS-like para separar patrones reales de viaje.';

comment on table public.route_pattern_stops is
  'Secuencia canonica de paradas por route_pattern. Equivale a una version ligera de stop_times sin horarios exactos.';

comment on table public.service_windows is
  'Ventanas de servicio por route_pattern, dia y franja horaria. Equivale a una capa ligera de frequencies/calendar.';

comment on column public.route_patterns.stop_signature is
  'Hash estable de la secuencia de paradas y flags pickup/dropoff. Permite detectar patrones equivalentes.';

comment on column public.service_windows.source_ruta_frecuencia_id is
  'Traza de migracion desde la fila legacy en ruta_frecuencias.';

with legacy_patterns as (
  select
    rp.ruta_id,
    rp.sentido,
    md5(
      string_agg(
        concat_ws(
          ':',
          rp.parada_id::text,
          rp.orden::text,
          case when rp.es_subida then '1' else '0' end,
          case when rp.es_bajada then '1' else '0' end
        ),
        '|'
        order by rp.orden asc
      )
    ) as stop_signature,
    count(*)::integer as parada_count,
    max(rp.distancia_acumulada_m) as distancia_total_m,
    (array_agg(rp.parada_id order by rp.orden asc))[1] as parada_inicial_id,
    (array_agg(rp.parada_id order by rp.orden desc))[1] as parada_final_id,
    (array_agg(coalesce(p.nombre, 'Parada de buses') order by rp.orden asc))[1] as parada_inicial_nombre,
    (array_agg(coalesce(p.nombre, 'Parada de buses') order by rp.orden desc))[1] as parada_final_nombre
  from public.ruta_paradas rp
  join public.paradas p
    on p.id = rp.parada_id
  group by rp.ruta_id, rp.sentido
)
insert into public.route_patterns (
  ruta_id,
  sentido,
  pattern_code,
  nombre,
  headsign,
  stop_signature,
  parada_inicial_id,
  parada_final_id,
  parada_count,
  distancia_total_m,
  activo,
  fuente,
  metadata
)
select
  lp.ruta_id,
  lp.sentido,
  concat('legacy-', lp.sentido, '-', substr(lp.stop_signature, 1, 12)) as pattern_code,
  concat(
    coalesce(r.nombre_ruta, concat('Ruta ', lp.ruta_id::text)),
    ' / ',
    upper(lp.sentido)
  ) as nombre,
  lp.parada_final_nombre as headsign,
  lp.stop_signature,
  lp.parada_inicial_id,
  lp.parada_final_id,
  lp.parada_count,
  lp.distancia_total_m,
  true,
  'legacy_migration',
  jsonb_build_object(
    'migrated_from', 'ruta_paradas',
    'legacy_ruta_id', lp.ruta_id,
    'legacy_sentido', lp.sentido
  )
from legacy_patterns lp
left join public.rutas r
  on r.id = lp.ruta_id
on conflict (ruta_id, sentido, pattern_code)
do update set
  nombre = excluded.nombre,
  headsign = excluded.headsign,
  stop_signature = excluded.stop_signature,
  parada_inicial_id = excluded.parada_inicial_id,
  parada_final_id = excluded.parada_final_id,
  parada_count = excluded.parada_count,
  distancia_total_m = excluded.distancia_total_m,
  activo = true,
  metadata = public.route_patterns.metadata || excluded.metadata,
  updated_at = timezone('utc', now());

with legacy_patterns as (
  select
    rp.ruta_id,
    rp.sentido,
    md5(
      string_agg(
        concat_ws(
          ':',
          rp.parada_id::text,
          rp.orden::text,
          case when rp.es_subida then '1' else '0' end,
          case when rp.es_bajada then '1' else '0' end
        ),
        '|'
        order by rp.orden asc
      )
    ) as stop_signature
  from public.ruta_paradas rp
  group by rp.ruta_id, rp.sentido
),
resolved_patterns as (
  select
    lp.ruta_id,
    lp.sentido,
    rp.id as pattern_id
  from legacy_patterns lp
  join public.route_patterns rp
    on rp.ruta_id = lp.ruta_id
   and rp.sentido = lp.sentido
   and rp.stop_signature = lp.stop_signature
   and rp.fuente = 'legacy_migration'
)
insert into public.route_pattern_stops (
  pattern_id,
  parada_id,
  stop_sequence,
  es_subida,
  es_bajada,
  pickup_type,
  drop_off_type,
  distancia_acumulada_m,
  tiempo_estimado_desde_inicio_min
)
select
  resolved.pattern_id,
  rp.parada_id,
  rp.orden as stop_sequence,
  rp.es_subida,
  rp.es_bajada,
  case when rp.es_subida then 0 else 1 end as pickup_type,
  case when rp.es_bajada then 0 else 1 end as drop_off_type,
  rp.distancia_acumulada_m,
  rp.tiempo_estimado_desde_inicio_min
from public.ruta_paradas rp
join resolved_patterns resolved
  on resolved.ruta_id = rp.ruta_id
 and resolved.sentido = rp.sentido
on conflict (pattern_id, stop_sequence)
do update set
  parada_id = excluded.parada_id,
  es_subida = excluded.es_subida,
  es_bajada = excluded.es_bajada,
  pickup_type = excluded.pickup_type,
  drop_off_type = excluded.drop_off_type,
  distancia_acumulada_m = excluded.distancia_acumulada_m,
  tiempo_estimado_desde_inicio_min = excluded.tiempo_estimado_desde_inicio_min,
  updated_at = timezone('utc', now());

insert into public.service_windows (
  pattern_id,
  dia_tipo,
  hora_inicio,
  hora_fin,
  frecuencia_promedio_min,
  activo,
  source_ruta_frecuencia_id,
  notas,
  metadata
)
select
  rp.id as pattern_id,
  rf.dia_tipo,
  rf.hora_inicio,
  rf.hora_fin,
  rf.frecuencia_promedio_min,
  rf.activo,
  rf.id as source_ruta_frecuencia_id,
  rf.notas,
  jsonb_build_object(
    'migrated_from', 'ruta_frecuencias',
    'legacy_ruta_id', rf.ruta_id,
    'legacy_sentido', rf.sentido
  )
from public.ruta_frecuencias rf
join public.route_patterns rp
  on rp.ruta_id = rf.ruta_id
 and rp.sentido = rf.sentido
 and rp.fuente = 'legacy_migration'
where not exists (
  select 1
  from public.service_windows sw
  where sw.pattern_id = rp.id
    and sw.source_ruta_frecuencia_id = rf.id
);
