set search_path = public, extensions;

create table if not exists public.route_trace_sessions (
  id bigint generated by default as identity primary key,
  client_trace_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  ruta_id integer references public.rutas(id) on delete set null,
  route_name text not null,
  route_code text,
  direction text not null default 'sin_definir',
  notes text,
  status text not null default 'pending_review',
  source text not null default 'mobile_trace',
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null,
  ended_at timestamptz,
  uploaded_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'route_trace_sessions_direction_chk'
      and conrelid = 'public.route_trace_sessions'::regclass
  ) then
    alter table public.route_trace_sessions
      add constraint route_trace_sessions_direction_chk
      check (direction in ('ida', 'vuelta', 'ambos', 'sin_definir'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'route_trace_sessions_status_chk'
      and conrelid = 'public.route_trace_sessions'::regclass
  ) then
    alter table public.route_trace_sessions
      add constraint route_trace_sessions_status_chk
      check (status in ('pending_review', 'reviewed', 'drafted', 'applied', 'rejected'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'route_trace_sessions_source_chk'
      and conrelid = 'public.route_trace_sessions'::regclass
  ) then
    alter table public.route_trace_sessions
      add constraint route_trace_sessions_source_chk
      check (source in ('mobile_trace', 'web_import', 'internal'));
  end if;
end $$;

create index if not exists route_trace_sessions_user_created_idx
  on public.route_trace_sessions (user_id, created_at desc);

create index if not exists route_trace_sessions_route_idx
  on public.route_trace_sessions (ruta_id, created_at desc);

create index if not exists route_trace_sessions_status_idx
  on public.route_trace_sessions (status, created_at desc);

create table if not exists public.route_trace_points (
  id bigint generated by default as identity primary key,
  trace_session_id bigint not null references public.route_trace_sessions(id) on delete cascade,
  point_order integer not null,
  captured_at timestamptz not null,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision,
  speed_mps double precision,
  heading_deg double precision,
  altitude_m double precision,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint route_trace_points_session_order_uidx unique (trace_session_id, point_order)
);

create index if not exists route_trace_points_session_order_idx
  on public.route_trace_points (trace_session_id, point_order);

create table if not exists public.route_change_drafts (
  id bigint generated by default as identity primary key,
  trace_session_id bigint references public.route_trace_sessions(id) on delete set null,
  ruta_id integer not null references public.rutas(id) on delete cascade,
  direction text not null default 'sin_definir',
  status text not null default 'draft',
  source text not null default 'trace_review',
  geometry jsonb not null,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id) on delete cascade,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'route_change_drafts_direction_chk'
      and conrelid = 'public.route_change_drafts'::regclass
  ) then
    alter table public.route_change_drafts
      add constraint route_change_drafts_direction_chk
      check (direction in ('ida', 'vuelta', 'ambos', 'sin_definir'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'route_change_drafts_status_chk'
      and conrelid = 'public.route_change_drafts'::regclass
  ) then
    alter table public.route_change_drafts
      add constraint route_change_drafts_status_chk
      check (status in ('draft', 'reviewed', 'applied', 'rejected'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'route_change_drafts_source_chk'
      and conrelid = 'public.route_change_drafts'::regclass
  ) then
    alter table public.route_change_drafts
      add constraint route_change_drafts_source_chk
      check (source in ('trace_review', 'manual_editor', 'internal'));
  end if;
end $$;

create index if not exists route_change_drafts_route_status_idx
  on public.route_change_drafts (ruta_id, status, created_at desc);

create index if not exists route_change_drafts_trace_idx
  on public.route_change_drafts (trace_session_id);

drop trigger if exists set_updated_at_route_trace_sessions on public.route_trace_sessions;
create trigger set_updated_at_route_trace_sessions
before update on public.route_trace_sessions
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_route_change_drafts on public.route_change_drafts;
create trigger set_updated_at_route_change_drafts
before update on public.route_change_drafts
for each row
execute function public.set_updated_at();

alter table public.route_trace_sessions enable row level security;
alter table public.route_trace_points enable row level security;
alter table public.route_change_drafts enable row level security;

grant select, insert on public.route_trace_sessions to authenticated;
grant select, insert on public.route_trace_points to authenticated;
grant select, insert, update (status, metadata, notes) on public.route_trace_sessions to authenticated;
grant select, insert, update on public.route_change_drafts to authenticated;

drop policy if exists route_trace_sessions_insert_authenticated on public.route_trace_sessions;
create policy route_trace_sessions_insert_authenticated
on public.route_trace_sessions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists route_trace_sessions_select_authenticated on public.route_trace_sessions;
create policy route_trace_sessions_select_authenticated
on public.route_trace_sessions
for select
to authenticated
using (true);

drop policy if exists route_trace_sessions_update_authenticated on public.route_trace_sessions;
create policy route_trace_sessions_update_authenticated
on public.route_trace_sessions
for update
to authenticated
using (true)
with check (true);

drop policy if exists route_trace_points_insert_authenticated on public.route_trace_points;
create policy route_trace_points_insert_authenticated
on public.route_trace_points
for insert
to authenticated
with check (
  exists (
    select 1
    from public.route_trace_sessions s
    where s.id = trace_session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists route_trace_points_select_authenticated on public.route_trace_points;
create policy route_trace_points_select_authenticated
on public.route_trace_points
for select
to authenticated
using (true);

drop policy if exists route_change_drafts_select_authenticated on public.route_change_drafts;
create policy route_change_drafts_select_authenticated
on public.route_change_drafts
for select
to authenticated
using (true);

drop policy if exists route_change_drafts_insert_authenticated on public.route_change_drafts;
create policy route_change_drafts_insert_authenticated
on public.route_change_drafts
for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists route_change_drafts_update_authenticated on public.route_change_drafts;
create policy route_change_drafts_update_authenticated
on public.route_change_drafts
for update
to authenticated
using (true)
with check (true);

comment on table public.route_trace_sessions is
  'Sesiones de trazado grabadas desde la app para comparar recorridos reales contra rutas existentes.';

comment on table public.route_trace_points is
  'Puntos GPS secuenciales de una sesion de trazado de ruta.';

comment on table public.route_change_drafts is
  'Borradores de cambio de trazado creados desde el portal web a partir de trazas reales o edicion interna.';
