set search_path = public, extensions;

create table if not exists public.route_geometry_versions (
  id bigint generated by default as identity primary key,
  ruta_id integer not null references public.rutas(id) on delete cascade,
  source_draft_id bigint references public.route_change_drafts(id) on delete set null,
  trace_session_id bigint references public.route_trace_sessions(id) on delete set null,
  restored_from_version_id bigint,
  version_kind text not null default 'manual_backup',
  geometry jsonb not null,
  point_count integer not null default 0,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'route_geometry_versions_kind_chk'
      and conrelid = 'public.route_geometry_versions'::regclass
  ) then
    alter table public.route_geometry_versions
      add constraint route_geometry_versions_kind_chk
      check (version_kind in ('backup_before_apply', 'backup_before_restore', 'manual_backup'));
  end if;
end $$;

create index if not exists route_geometry_versions_route_created_idx
  on public.route_geometry_versions (ruta_id, created_at desc);

create index if not exists route_geometry_versions_source_draft_idx
  on public.route_geometry_versions (source_draft_id);

create index if not exists route_geometry_versions_trace_idx
  on public.route_geometry_versions (trace_session_id);

alter table public.route_geometry_versions enable row level security;

grant select on public.route_geometry_versions to authenticated;

drop policy if exists route_geometry_versions_select_authenticated on public.route_geometry_versions;
create policy route_geometry_versions_select_authenticated
on public.route_geometry_versions
for select
to authenticated
using (true);

create or replace function public._route_geometry_json_for_route(
  p_ruta_id integer
)
returns jsonb
language sql
stable
security definer
set search_path = public, extensions
as $$
  with segments as (
    select
      coalesce(rp.segmento_id, 0) as segmento_id,
      jsonb_agg(jsonb_build_array(rp.lng, rp.lat) order by rp.orden) as coords
    from public.ruta_puntos rp
    where rp.ruta_id = p_ruta_id
    group by coalesce(rp.segmento_id, 0)
    order by coalesce(rp.segmento_id, 0)
  )
  select case
    when (select count(*) from segments) = 0 then null
    when (select count(*) from segments) = 1 then jsonb_build_object(
      'type', 'LineString',
      'coordinates', (select coords from segments limit 1)
    )
    else jsonb_build_object(
      'type', 'MultiLineString',
      'coordinates', (select jsonb_agg(coords order by segmento_id) from segments)
    )
  end;
$$;

create or replace function public._apply_route_geometry_json(
  p_ruta_id integer,
  p_geometry jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_geometry_type text := coalesce(p_geometry->>'type', '');
  v_inserted integer := 0;
begin
  if p_geometry is null then
    raise exception 'La geometria de ruta no puede ser null';
  end if;

  if v_geometry_type not in ('LineString', 'MultiLineString') then
    raise exception 'Tipo de geometria no soportado: %', v_geometry_type;
  end if;

  delete from public.ruta_puntos rp
  where rp.ruta_id = p_ruta_id;

  if v_geometry_type = 'LineString' then
    with coords as (
      select
        ordinality - 1 as orden,
        (value->>0)::double precision as lng,
        (value->>1)::double precision as lat
      from jsonb_array_elements(p_geometry->'coordinates') with ordinality
    )
    insert into public.ruta_puntos (
      ruta_id,
      lat,
      lng,
      orden,
      geog,
      segmento_id
    )
    select
      p_ruta_id,
      coords.lat,
      coords.lng,
      coords.orden,
      st_setsrid(st_makepoint(coords.lng, coords.lat), 4326)::geography,
      0
    from coords
    order by coords.orden;
  else
    with segments as (
      select
        seg.ordinality - 1 as segmento_id,
        seg.value as segment_points
      from jsonb_array_elements(p_geometry->'coordinates') with ordinality as seg(value, ordinality)
    ),
    coords as (
      select
        segments.segmento_id,
        pt.ordinality - 1 as orden,
        (pt.value->>0)::double precision as lng,
        (pt.value->>1)::double precision as lat
      from segments
      cross join lateral jsonb_array_elements(segments.segment_points) with ordinality as pt(value, ordinality)
    )
    insert into public.ruta_puntos (
      ruta_id,
      lat,
      lng,
      orden,
      geog,
      segmento_id
    )
    select
      p_ruta_id,
      coords.lat,
      coords.lng,
      coords.orden,
      st_setsrid(st_makepoint(coords.lng, coords.lat), 4326)::geography,
      coords.segmento_id
    from coords
    order by coords.segmento_id, coords.orden;
  end if;

  get diagnostics v_inserted = row_count;

  update public.rutas
  set geometry = p_geometry
  where id = p_ruta_id;

  return v_inserted;
end;
$$;

create or replace function public.crear_route_geometry_backup(
  p_ruta_id integer,
  p_notes text default null,
  p_version_kind text default 'manual_backup'
)
returns table (
  version_id bigint,
  ruta_id integer,
  point_count integer,
  version_kind text,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_geometry jsonb;
  v_point_count integer := 0;
  v_version_id bigint;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesion para crear un backup';
  end if;

  if p_version_kind not in ('backup_before_apply', 'backup_before_restore', 'manual_backup') then
    raise exception 'version_kind no soportado: %', p_version_kind;
  end if;

  v_geometry := public._route_geometry_json_for_route(p_ruta_id);

  if v_geometry is null then
    raise exception 'La ruta % no tiene trazado actual para respaldar', p_ruta_id;
  end if;

  select count(*)
  into v_point_count
  from public.ruta_puntos rp
  where rp.ruta_id = p_ruta_id;

  insert into public.route_geometry_versions (
    ruta_id,
    version_kind,
    geometry,
    point_count,
    notes,
    metadata,
    created_by
  )
  values (
    p_ruta_id,
    p_version_kind,
    v_geometry,
    v_point_count,
    nullif(trim(p_notes), ''),
    jsonb_build_object(
      'created_from', 'manual_backup_rpc',
      'captured_at', timezone('utc', now())
    ),
    v_user_id
  )
  returning id into v_version_id;

  return query
  select
    v_version_id,
    p_ruta_id,
    v_point_count,
    p_version_kind,
    'saved'::text;
end;
$$;

create or replace function public.restaurar_route_geometry_version(
  p_version_id bigint
)
returns table (
  version_id bigint,
  ruta_id integer,
  inserted_points integer,
  backup_created_id bigint,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_version public.route_geometry_versions%rowtype;
  v_current_geometry jsonb;
  v_current_points integer := 0;
  v_backup_id bigint := null;
  v_inserted integer := 0;
  v_now timestamptz := timezone('utc', now());
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesion para restaurar un backup';
  end if;

  select *
  into v_version
  from public.route_geometry_versions
  where id = p_version_id;

  if not found then
    raise exception 'No existe el backup de ruta %', p_version_id;
  end if;

  v_current_geometry := public._route_geometry_json_for_route(v_version.ruta_id);

  if v_current_geometry is not null then
    select count(*)
    into v_current_points
    from public.ruta_puntos rp
    where rp.ruta_id = v_version.ruta_id;

    insert into public.route_geometry_versions (
      ruta_id,
      source_draft_id,
      trace_session_id,
      restored_from_version_id,
      version_kind,
      geometry,
      point_count,
      notes,
      metadata,
      created_by
    )
    values (
      v_version.ruta_id,
      null,
      null,
      p_version_id,
      'backup_before_restore',
      v_current_geometry,
      v_current_points,
      format('Backup automatico antes de restaurar la version %s', p_version_id),
      jsonb_build_object(
        'restoring_version_id', p_version_id,
        'captured_at', v_now,
        'restored_by', v_user_id
      ),
      v_user_id
    )
    returning id into v_backup_id;
  end if;

  v_inserted := public._apply_route_geometry_json(v_version.ruta_id, v_version.geometry);

  return query
  select
    p_version_id,
    v_version.ruta_id,
    v_inserted,
    v_backup_id,
    'restored'::text;
end;
$$;

create or replace function public.deshacer_ultimo_cambio_ruta(
  p_ruta_id integer
)
returns table (
  version_id bigint,
  ruta_id integer,
  inserted_points integer,
  backup_created_id bigint,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_version_id bigint;
begin
  select rv.id
  into v_version_id
  from public.route_geometry_versions rv
  where rv.ruta_id = p_ruta_id
  order by rv.created_at desc, rv.id desc
  limit 1;

  if v_version_id is null then
    raise exception 'La ruta % todavia no tiene backups para restaurar', p_ruta_id;
  end if;

  return query
  select *
  from public.restaurar_route_geometry_version(v_version_id);
end;
$$;

create or replace function public.aplicar_route_change_draft(
  p_draft_id bigint
)
returns table (
  draft_id bigint,
  ruta_id integer,
  inserted_points integer,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_draft public.route_change_drafts%rowtype;
  v_trace_id bigint;
  v_geometry jsonb;
  v_geometry_kind text;
  v_now timestamptz := timezone('utc', now());
  v_user_id uuid := auth.uid();
  v_inserted integer := 0;
  v_backup_id bigint := null;
  v_current_geometry jsonb;
  v_current_points integer := 0;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesion para aplicar un borrador';
  end if;

  select d.*, d.trace_session_id
  into v_draft
  from public.route_change_drafts d
  where d.id = p_draft_id;

  if not found then
    raise exception 'No existe el borrador %', p_draft_id;
  end if;

  v_trace_id := v_draft.trace_session_id;

  select
    feature->'geometry',
    coalesce(feature->'properties'->>'kind', '')
  into v_geometry, v_geometry_kind
  from jsonb_array_elements(coalesce(v_draft.geometry->'features', '[]'::jsonb)) feature
  where coalesce(feature->'properties'->>'kind', '') in ('captured_trace', 'edited_route')
  limit 1;

  if v_geometry is null or coalesce(v_geometry->>'type', '') not in ('LineString', 'MultiLineString') then
    raise exception 'El borrador % no tiene una geometria valida para aplicar', p_draft_id;
  end if;

  v_current_geometry := public._route_geometry_json_for_route(v_draft.ruta_id);

  if v_current_geometry is not null then
    select count(*)
    into v_current_points
    from public.ruta_puntos rp
    where rp.ruta_id = v_draft.ruta_id;

    insert into public.route_geometry_versions (
      ruta_id,
      source_draft_id,
      trace_session_id,
      version_kind,
      geometry,
      point_count,
      notes,
      metadata,
      created_by
    )
    values (
      v_draft.ruta_id,
      p_draft_id,
      v_trace_id,
      'backup_before_apply',
      v_current_geometry,
      v_current_points,
      format('Backup automatico antes de aplicar el borrador %s', p_draft_id),
      jsonb_build_object(
        'draft_id', p_draft_id,
        'geometry_kind', v_geometry_kind,
        'captured_at', v_now
      ),
      v_user_id
    )
    returning id into v_backup_id;
  end if;

  v_inserted := public._apply_route_geometry_json(v_draft.ruta_id, v_geometry);

  update public.route_change_drafts
  set
    status = 'applied',
    reviewed_by = v_user_id,
    reviewed_at = v_now,
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'applied_at', v_now,
      'applied_by', v_user_id,
      'applied_points', v_inserted,
      'applied_geometry_kind', v_geometry_kind,
      'backup_version_id', v_backup_id
    )
  where id = p_draft_id;

  if v_trace_id is not null then
    update public.route_trace_sessions
    set
      status = 'applied',
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
        'last_applied_draft_id', p_draft_id,
        'last_applied_at', v_now,
        'last_applied_by', v_user_id,
        'last_applied_points', v_inserted,
        'last_applied_geometry_kind', v_geometry_kind,
        'last_backup_version_id', v_backup_id
      )
    where id = v_trace_id;
  end if;

  return query
  select
    p_draft_id,
    v_draft.ruta_id,
    v_inserted,
    'applied'::text;
end;
$$;

revoke all on function public._route_geometry_json_for_route(integer) from public, anon, authenticated;
revoke all on function public._apply_route_geometry_json(integer, jsonb) from public, anon, authenticated;

create or replace function public.eliminar_route_geometry_version(
  p_version_id bigint
)
returns table (
  version_id bigint,
  ruta_id integer,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $
declare
  v_user_id uuid := auth.uid();
  v_version public.route_geometry_versions%rowtype;
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesion para borrar un backup';
  end if;

  select *
  into v_version
  from public.route_geometry_versions
  where id = p_version_id;

  if not found then
    raise exception 'No existe el backup de ruta %', p_version_id;
  end if;

  delete from public.route_geometry_versions
  where id = p_version_id;

  return query
  select
    p_version_id,
    v_version.ruta_id,
    'deleted'::text;
end;
$;

grant execute on function public.crear_route_geometry_backup(integer, text, text)
  to authenticated;

grant execute on function public.restaurar_route_geometry_version(bigint)
  to authenticated;

grant execute on function public.deshacer_ultimo_cambio_ruta(integer)
  to authenticated;

grant execute on function public.eliminar_route_geometry_version(bigint)
  to authenticated;

grant execute on function public.aplicar_route_change_draft(bigint)
  to authenticated;

comment on table public.route_geometry_versions is
  'Backups/versiones de trazados de rutas para poder restaurar cambios y mantener historial operativo.';

comment on function public.crear_route_geometry_backup(integer, text, text) is
  'Crea un backup manual del trazado actual de una ruta para permitir undo/restauracion posterior.';

comment on function public.restaurar_route_geometry_version(bigint) is
  'Restaura una version/back-up de trazado sobre ruta_puntos y rutas.geometry, creando antes un backup del estado actual.';

comment on function public.deshacer_ultimo_cambio_ruta(integer) is
  'Restaura el backup mas reciente disponible para una ruta, dejando a la vez un backup del estado previo al undo.';

comment on function public.eliminar_route_geometry_version(bigint) is
  'Elimina un backup/version de trazado desde el portal interno cuando ya no hace falta conservarlo.';

comment on function public.aplicar_route_change_draft(bigint) is
  'Aplica un borrador de cambio de trazado sobre ruta_puntos dejando primero un backup automatico del trazado actual.';
