set search_path = public, extensions;

create extension if not exists btree_gist with schema extensions;

-- Capa operativa: la frecuencia no vive en paradas.
-- Esta tabla modela la cadencia esperada por ruta, sentido y franja horaria.
create table if not exists public.ruta_frecuencias (
  id bigint generated by default as identity primary key,
  ruta_id bigint not null references public.rutas(id) on delete cascade,
  sentido text not null default 'ida',
  dia_tipo text not null default 'habil',
  hora_inicio time not null,
  hora_fin time not null,
  frecuencia_promedio_min integer not null,
  espera_promedio_min integer generated always as (
    greatest(1, ceil(frecuencia_promedio_min::numeric / 2.0)::integer)
  ) stored,
  minuto_inicio integer generated always as (
    extract(hour from hora_inicio)::integer * 60
    + extract(minute from hora_inicio)::integer
  ) stored,
  minuto_fin integer generated always as (
    extract(hour from hora_fin)::integer * 60
    + extract(minute from hora_fin)::integer
  ) stored,
  activo boolean not null default true,
  notas text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_frecuencias_sentido_chk'
      and conrelid = 'public.ruta_frecuencias'::regclass
  ) then
    alter table public.ruta_frecuencias
      add constraint ruta_frecuencias_sentido_chk
      check (sentido in ('ida', 'vuelta', 'loop', 'ambos'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_frecuencias_dia_tipo_chk'
      and conrelid = 'public.ruta_frecuencias'::regclass
  ) then
    alter table public.ruta_frecuencias
      add constraint ruta_frecuencias_dia_tipo_chk
      check (dia_tipo in ('habil', 'sabado', 'domingo', 'feriado'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_frecuencias_hora_rango_chk'
      and conrelid = 'public.ruta_frecuencias'::regclass
  ) then
    alter table public.ruta_frecuencias
      add constraint ruta_frecuencias_hora_rango_chk
      check (hora_fin > hora_inicio);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_frecuencias_valor_chk'
      and conrelid = 'public.ruta_frecuencias'::regclass
  ) then
    alter table public.ruta_frecuencias
      add constraint ruta_frecuencias_valor_chk
      check (frecuencia_promedio_min between 1 and 240);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_frecuencias_no_overlap_excl'
      and conrelid = 'public.ruta_frecuencias'::regclass
  ) then
    alter table public.ruta_frecuencias
      add constraint ruta_frecuencias_no_overlap_excl
      exclude using gist (
        ruta_id with =,
        sentido with =,
        dia_tipo with =,
        int4range(minuto_inicio, minuto_fin, '[)') with &&
      )
      where (activo);
  end if;
end $$;

create index if not exists ruta_frecuencias_lookup_idx
  on public.ruta_frecuencias (ruta_id, sentido, dia_tipo, hora_inicio, hora_fin)
  where activo = true;

create index if not exists ruta_frecuencias_route_day_idx
  on public.ruta_frecuencias (ruta_id, dia_tipo)
  where activo = true;

create index if not exists ruta_frecuencias_active_idx
  on public.ruta_frecuencias (activo)
  where activo = true;

drop trigger if exists set_updated_at_ruta_frecuencias on public.ruta_frecuencias;
create trigger set_updated_at_ruta_frecuencias
before update on public.ruta_frecuencias
for each row
execute function public.set_updated_at();

alter table public.ruta_frecuencias enable row level security;

drop policy if exists ruta_frecuencias_read_public on public.ruta_frecuencias;
create policy ruta_frecuencias_read_public
on public.ruta_frecuencias
for select
to anon, authenticated
using (true);

comment on table public.ruta_frecuencias is
  'Frecuencia operativa promedio por ruta, sentido y franja horaria. Capa separada de la red de paradas.';

comment on column public.ruta_frecuencias.espera_promedio_min is
  'Espera promedio estimada; normalmente la mitad de la frecuencia.';

-- Datos de ejemplo para la variante Cartago-Taras-San Nicolas.
-- Importante: el codigo CTP 323 no es unico en este dataset, asi que la semilla
-- debe priorizar la variante Taras/San Nicolas por nombre antes de caer en un
-- fallback mas amplio por codigo.
-- Sustituyelos por horarios oficiales si ya los tienes verificados.
do $$
declare
  v_ruta_id bigint;
begin
  select r.id
  into v_ruta_id
  from public.rutas r
  order by
    case
      when upper(coalesce(r.nombre_ruta, '')) like '%TARAS%'
       and upper(coalesce(r.nombre_ruta, '')) like '%SAN NICOLAS%'
       and upper(trim(coalesce(r.codigo_ctp, ''))) = '323' then 0
      when upper(coalesce(r.nombre_ruta, '')) like '%TARAS%'
       and upper(trim(coalesce(r.codigo_ctp, ''))) = '323' then 1
      when upper(coalesce(r.nombre_ruta, '')) like '%TARAS%'
       and upper(coalesce(r.nombre_ruta, '')) like '%CARTAGO%' then 2
      when upper(trim(coalesce(r.codigo_ctp, ''))) = '323' then 3
      else 4
    end,
    r.id
  limit 1;

  if v_ruta_id is null or not exists (
    select 1
    from public.rutas r
    where r.id = v_ruta_id
      and (
        upper(trim(coalesce(r.codigo_ctp, ''))) = '323'
        or upper(coalesce(r.nombre_ruta, '')) like '%TARAS%'
      )
  ) then
    raise notice 'No se encontro una variante Taras/San Nicolas apta para sembrar frecuencias. La semilla no fue insertada.';
    return;
  end if;

  insert into public.ruta_frecuencias (
    ruta_id,
    sentido,
    dia_tipo,
    hora_inicio,
    hora_fin,
    frecuencia_promedio_min,
    activo,
    notas
  )
  values
    (v_ruta_id, 'ida',    'habil',   time '04:30', time '06:00', 12, true, 'Semilla operativa Taras-Cartago madrugada laboral'),
    (v_ruta_id, 'ida',    'habil',   time '06:00', time '09:00',  7, true, 'Semilla operativa Taras-Cartago hora pico am'),
    (v_ruta_id, 'ida',    'habil',   time '09:00', time '12:00', 10, true, 'Semilla operativa Taras-Cartago media manana'),
    (v_ruta_id, 'ida',    'habil',   time '12:00', time '15:30',  9, true, 'Semilla operativa Taras-Cartago mediodia'),
    (v_ruta_id, 'ida',    'habil',   time '15:30', time '19:00',  7, true, 'Semilla operativa Taras-Cartago hora pico pm'),
    (v_ruta_id, 'ida',    'habil',   time '19:00', time '22:00', 14, true, 'Semilla operativa Taras-Cartago noche'),

    (v_ruta_id, 'vuelta', 'habil',   time '04:30', time '06:00', 12, true, 'Semilla operativa Cartago-Taras madrugada laboral'),
    (v_ruta_id, 'vuelta', 'habil',   time '06:00', time '09:00',  7, true, 'Semilla operativa Cartago-Taras hora pico am'),
    (v_ruta_id, 'vuelta', 'habil',   time '09:00', time '12:00', 10, true, 'Semilla operativa Cartago-Taras media manana'),
    (v_ruta_id, 'vuelta', 'habil',   time '12:00', time '15:30',  9, true, 'Semilla operativa Cartago-Taras mediodia'),
    (v_ruta_id, 'vuelta', 'habil',   time '15:30', time '19:00',  7, true, 'Semilla operativa Cartago-Taras hora pico pm'),
    (v_ruta_id, 'vuelta', 'habil',   time '19:00', time '22:00', 14, true, 'Semilla operativa Cartago-Taras noche'),

    (v_ruta_id, 'ida',    'sabado',  time '05:00', time '08:00', 10, true, 'Semilla operativa Taras-Cartago sabado temprano'),
    (v_ruta_id, 'ida',    'sabado',  time '08:00', time '14:00', 12, true, 'Semilla operativa Taras-Cartago sabado dia'),
    (v_ruta_id, 'ida',    'sabado',  time '14:00', time '19:00', 10, true, 'Semilla operativa Taras-Cartago sabado tarde'),
    (v_ruta_id, 'ida',    'sabado',  time '19:00', time '22:00', 16, true, 'Semilla operativa Taras-Cartago sabado noche'),

    (v_ruta_id, 'vuelta', 'sabado',  time '05:00', time '08:00', 10, true, 'Semilla operativa Cartago-Taras sabado temprano'),
    (v_ruta_id, 'vuelta', 'sabado',  time '08:00', time '14:00', 12, true, 'Semilla operativa Cartago-Taras sabado dia'),
    (v_ruta_id, 'vuelta', 'sabado',  time '14:00', time '19:00', 10, true, 'Semilla operativa Cartago-Taras sabado tarde'),
    (v_ruta_id, 'vuelta', 'sabado',  time '19:00', time '22:00', 16, true, 'Semilla operativa Cartago-Taras sabado noche'),

    (v_ruta_id, 'ida',    'domingo', time '05:30', time '09:00', 15, true, 'Semilla operativa Taras-Cartago domingo am'),
    (v_ruta_id, 'ida',    'domingo', time '09:00', time '18:00', 18, true, 'Semilla operativa Taras-Cartago domingo dia'),
    (v_ruta_id, 'ida',    'domingo', time '18:00', time '21:30', 20, true, 'Semilla operativa Taras-Cartago domingo noche'),

    (v_ruta_id, 'vuelta', 'domingo', time '05:30', time '09:00', 15, true, 'Semilla operativa Cartago-Taras domingo am'),
    (v_ruta_id, 'vuelta', 'domingo', time '09:00', time '18:00', 18, true, 'Semilla operativa Cartago-Taras domingo dia'),
    (v_ruta_id, 'vuelta', 'domingo', time '18:00', time '21:30', 20, true, 'Semilla operativa Cartago-Taras domingo noche')
  on conflict do nothing;
end $$;

create or replace function public.buscar_viajes_0_1_transbordo_v2(
  p_origen_lat double precision,
  p_origen_lng double precision,
  p_destino_lat double precision,
  p_destino_lng double precision,
  p_radio_origen_m integer default 600,
  p_radio_destino_m integer default 600,
  p_max_caminar_transbordo_m integer default 180,
  p_max_resultados integer default 12,
  p_sentido text default null,
  p_fecha_hora timestamptz default timezone('utc', now()),
  p_es_feriado boolean default false,
  p_espera_default_min integer default 12
)
returns table (
  tipo_viaje text,
  transbordos integer,
  score numeric,
  ruta_1_id bigint,
  ruta_1_nombre text,
  ruta_1_codigo text,
  ruta_1_operador text,
  sentido_1 text,
  subida_1_parada_id bigint,
  subida_1_parada_nombre text,
  subida_1_distancia_m integer,
  bajada_1_parada_id bigint,
  bajada_1_parada_nombre text,
  ruta_2_id bigint,
  ruta_2_nombre text,
  ruta_2_codigo text,
  ruta_2_operador text,
  sentido_2 text,
  subida_2_parada_id bigint,
  subida_2_parada_nombre text,
  bajada_2_parada_id bigint,
  bajada_2_parada_nombre text,
  transbordo_distancia_m integer,
  destino_distancia_final_m integer,
  caminata_total_m integer,
  tiempo_caminando_total_min integer,
  espera_1_min integer,
  espera_2_min integer,
  espera_total_min integer,
  frecuencia_1_min integer,
  frecuencia_2_min integer,
  dia_tipo_aplicado text,
  hora_local_aplicada time,
  tarifa_total numeric
)
language sql
stable
set search_path = public, extensions
as $$
with
contexto as (
  select
    st_setsrid(st_makepoint(p_origen_lng, p_origen_lat), 4326)::geography as origen_geo,
    st_setsrid(st_makepoint(p_destino_lng, p_destino_lat), 4326)::geography as destino_geo,
    (p_fecha_hora at time zone 'America/Costa_Rica')::time as hora_local,
    case
      when p_es_feriado then 'feriado'
      when extract(dow from (p_fecha_hora at time zone 'America/Costa_Rica')) = 0 then 'domingo'
      when extract(dow from (p_fecha_hora at time zone 'America/Costa_Rica')) = 6 then 'sabado'
      else 'habil'
    end::text as dia_tipo_actual
),
latest_fares as (
  select distinct on (upper(trim(t.codigo_ruta)))
    upper(trim(t.codigo_ruta)) as codigo_ruta_key,
    t.tarifa_regular
  from public.tarifas t
  where t.codigo_ruta is not null
  order by upper(trim(t.codigo_ruta)), t.fecha_vigencia desc nulls last, t.id desc
),
origin_nearby_stops as (
  select
    p.id as parada_id,
    p.nombre as parada_nombre,
    st_distance(p.geo, c.origen_geo)::integer as origen_distancia_m
  from contexto c
  join public.paradas p
    on p.activo = true
   and st_dwithin(p.geo, c.origen_geo, p_radio_origen_m)
),
origin_candidates_raw as (
  select
    rp.ruta_id,
    rp.sentido,
    rp.parada_id,
    rp.orden,
    r.nombre_ruta as ruta_nombre,
    r.codigo_ctp as ruta_codigo,
    r.operador as ruta_operador,
    ons.parada_nombre,
    ons.origen_distancia_m,
    row_number() over (
      partition by rp.ruta_id, rp.sentido
      order by ons.origen_distancia_m asc, rp.orden asc, rp.parada_id asc
    ) as rn_ruta,
    row_number() over (
      order by ons.origen_distancia_m asc, rp.ruta_id asc, rp.sentido asc, rp.orden asc
    ) as rn_global
  from origin_nearby_stops ons
  join public.ruta_paradas rp
    on rp.parada_id = ons.parada_id
   and rp.es_subida = true
  join public.rutas r on r.id = rp.ruta_id
  where p_sentido is null or rp.sentido = p_sentido
),
origin_candidates as (
  select
    ocr.ruta_id,
    ocr.sentido,
    ocr.parada_id,
    ocr.orden,
    ocr.ruta_nombre,
    ocr.ruta_codigo,
    ocr.ruta_operador,
    ocr.parada_nombre,
    ocr.origen_distancia_m
  from origin_candidates_raw ocr
  where ocr.rn_ruta <= 3
    and ocr.rn_global <= 80
),
destination_nearby_stops as (
  select
    p.id as parada_id,
    p.nombre as parada_nombre,
    st_distance(p.geo, c.destino_geo)::integer as destino_distancia_m
  from contexto c
  join public.paradas p
    on p.activo = true
   and st_dwithin(p.geo, c.destino_geo, p_radio_destino_m)
),
destination_candidates_raw as (
  select
    rp.ruta_id,
    rp.sentido,
    rp.parada_id,
    rp.orden,
    r.nombre_ruta as ruta_nombre,
    r.codigo_ctp as ruta_codigo,
    r.operador as ruta_operador,
    dns.parada_nombre,
    dns.destino_distancia_m,
    row_number() over (
      partition by rp.ruta_id, rp.sentido
      order by dns.destino_distancia_m asc, rp.orden asc, rp.parada_id asc
    ) as rn_ruta,
    row_number() over (
      order by dns.destino_distancia_m asc, rp.ruta_id asc, rp.sentido asc, rp.orden asc
    ) as rn_global
  from destination_nearby_stops dns
  join public.ruta_paradas rp
    on rp.parada_id = dns.parada_id
   and rp.es_bajada = true
  join public.rutas r on r.id = rp.ruta_id
  where p_sentido is null or rp.sentido = p_sentido
),
destination_candidates as (
  select
    dcr.ruta_id,
    dcr.sentido,
    dcr.parada_id,
    dcr.orden,
    dcr.ruta_nombre,
    dcr.ruta_codigo,
    dcr.ruta_operador,
    dcr.parada_nombre,
    dcr.destino_distancia_m
  from destination_candidates_raw dcr
  where dcr.rn_ruta <= 3
    and dcr.rn_global <= 80
),
transbordos_expandido as (
  select
    t.parada_origen_id,
    t.parada_destino_id,
    t.distancia_caminando_m
  from public.transbordos t
  where t.activo = true
    and t.distancia_caminando_m <= p_max_caminar_transbordo_m

  union all

  select
    t.parada_destino_id as parada_origen_id,
    t.parada_origen_id as parada_destino_id,
    t.distancia_caminando_m
  from public.transbordos t
  where t.activo = true
    and t.bidireccional = true
    and t.distancia_caminando_m <= p_max_caminar_transbordo_m
),
direct_ranked as (
  select
    'directo'::text as tipo_viaje,
    0 as transbordos,
    (
      greatest(1, round((o.origen_distancia_m + d.destino_distancia_m) / 80.0))
      + coalesce(freq1.espera_promedio_min, p_espera_default_min)
      + coalesce(f1.tarifa_regular / 150.0, 0)
    )::numeric as score,
    o.ruta_id as ruta_1_id,
    o.ruta_nombre as ruta_1_nombre,
    o.ruta_codigo as ruta_1_codigo,
    o.ruta_operador as ruta_1_operador,
    o.sentido as sentido_1,
    o.parada_id as subida_1_parada_id,
    coalesce(o.parada_nombre, 'Parada de buses') as subida_1_parada_nombre,
    o.origen_distancia_m as subida_1_distancia_m,
    d.parada_id as bajada_1_parada_id,
    coalesce(d.parada_nombre, 'Parada de buses') as bajada_1_parada_nombre,
    null::bigint as ruta_2_id,
    null::text as ruta_2_nombre,
    null::text as ruta_2_codigo,
    null::text as ruta_2_operador,
    null::text as sentido_2,
    null::bigint as subida_2_parada_id,
    null::text as subida_2_parada_nombre,
    null::bigint as bajada_2_parada_id,
    null::text as bajada_2_parada_nombre,
    null::integer as transbordo_distancia_m,
    d.destino_distancia_m as destino_distancia_final_m,
    (o.origen_distancia_m + d.destino_distancia_m)::integer as caminata_total_m,
    greatest(1, round((o.origen_distancia_m + d.destino_distancia_m) / 80.0))::integer as tiempo_caminando_total_min,
    coalesce(freq1.espera_promedio_min, p_espera_default_min)::integer as espera_1_min,
    null::integer as espera_2_min,
    coalesce(freq1.espera_promedio_min, p_espera_default_min)::integer as espera_total_min,
    freq1.frecuencia_promedio_min::integer as frecuencia_1_min,
    null::integer as frecuencia_2_min,
    c.dia_tipo_actual as dia_tipo_aplicado,
    c.hora_local as hora_local_aplicada,
    f1.tarifa_regular::numeric as tarifa_total,
    row_number() over (
      partition by o.ruta_id, o.sentido
      order by
        (
          greatest(1, round((o.origen_distancia_m + d.destino_distancia_m) / 80.0))
          + coalesce(freq1.espera_promedio_min, p_espera_default_min)
          + coalesce(f1.tarifa_regular / 150.0, 0)
        ) asc,
        (d.orden - o.orden) desc
    ) as rn
  from contexto c
  join origin_candidates o on true
  join destination_candidates d
    on d.ruta_id = o.ruta_id
   and d.sentido = o.sentido
   and d.orden > o.orden
  left join latest_fares f1
    on f1.codigo_ruta_key = upper(trim(o.ruta_codigo))
  left join lateral (
    select
      rf.frecuencia_promedio_min,
      rf.espera_promedio_min
    from public.ruta_frecuencias rf
    where rf.ruta_id = o.ruta_id
      and rf.activo = true
      and rf.dia_tipo = c.dia_tipo_actual
      and c.hora_local >= rf.hora_inicio
      and c.hora_local < rf.hora_fin
      and rf.sentido in (o.sentido, 'ambos')
    order by case when rf.sentido = o.sentido then 0 else 1 end, rf.hora_inicio desc
    limit 1
  ) freq1 on true
),
direct_best as (
  select
    tipo_viaje,
    transbordos,
    score,
    ruta_1_id,
    ruta_1_nombre,
    ruta_1_codigo,
    ruta_1_operador,
    sentido_1,
    subida_1_parada_id,
    subida_1_parada_nombre,
    subida_1_distancia_m,
    bajada_1_parada_id,
    bajada_1_parada_nombre,
    ruta_2_id,
    ruta_2_nombre,
    ruta_2_codigo,
    ruta_2_operador,
    sentido_2,
    subida_2_parada_id,
    subida_2_parada_nombre,
    bajada_2_parada_id,
    bajada_2_parada_nombre,
    transbordo_distancia_m,
    destino_distancia_final_m,
    caminata_total_m,
    tiempo_caminando_total_min,
    espera_1_min,
    espera_2_min,
    espera_total_min,
    frecuencia_1_min,
    frecuencia_2_min,
    dia_tipo_aplicado,
    hora_local_aplicada,
    tarifa_total
  from direct_ranked
  where rn = 1
),
allow_transfer_search as (
  select count(*) < 3 as run_transfer
  from direct_best
),
destination_route_scope as (
  select distinct
    d.ruta_id,
    d.sentido
  from destination_candidates d
),
transfer_ranked as (
  select
    'transbordo'::text as tipo_viaje,
    1 as transbordos,
    (
      greatest(1, round((o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m) / 80.0))
      + coalesce(freq1.espera_promedio_min, p_espera_default_min)
      + coalesce(freq2.espera_promedio_min, p_espera_default_min)
      + 4
      + coalesce(f1.tarifa_regular / 150.0, 0)
      + coalesce(f2.tarifa_regular / 150.0, 0)
    )::numeric as score,
    o.ruta_id as ruta_1_id,
    o.ruta_nombre as ruta_1_nombre,
    o.ruta_codigo as ruta_1_codigo,
    o.ruta_operador as ruta_1_operador,
    o.sentido as sentido_1,
    o.parada_id as subida_1_parada_id,
    coalesce(o.parada_nombre, 'Parada de buses') as subida_1_parada_nombre,
    o.origen_distancia_m as subida_1_distancia_m,
    rp1_alight.parada_id as bajada_1_parada_id,
    coalesce(p1_alight.nombre, 'Parada de buses') as bajada_1_parada_nombre,
    rp2_board.ruta_id as ruta_2_id,
    r2.nombre_ruta as ruta_2_nombre,
    r2.codigo_ctp as ruta_2_codigo,
    r2.operador as ruta_2_operador,
    rp2_board.sentido as sentido_2,
    rp2_board.parada_id as subida_2_parada_id,
    coalesce(p2_board.nombre, 'Parada de buses') as subida_2_parada_nombre,
    d.parada_id as bajada_2_parada_id,
    coalesce(d.parada_nombre, 'Parada de buses') as bajada_2_parada_nombre,
    tx.distancia_caminando_m as transbordo_distancia_m,
    d.destino_distancia_m as destino_distancia_final_m,
    (o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m)::integer as caminata_total_m,
    greatest(1, round((o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m) / 80.0))::integer as tiempo_caminando_total_min,
    coalesce(freq1.espera_promedio_min, p_espera_default_min)::integer as espera_1_min,
    coalesce(freq2.espera_promedio_min, p_espera_default_min)::integer as espera_2_min,
    (
      coalesce(freq1.espera_promedio_min, p_espera_default_min)
      + coalesce(freq2.espera_promedio_min, p_espera_default_min)
    )::integer as espera_total_min,
    freq1.frecuencia_promedio_min::integer as frecuencia_1_min,
    freq2.frecuencia_promedio_min::integer as frecuencia_2_min,
    c.dia_tipo_actual as dia_tipo_aplicado,
    c.hora_local as hora_local_aplicada,
    case
      when f1.tarifa_regular is null and f2.tarifa_regular is null then null
      else (coalesce(f1.tarifa_regular, 0) + coalesce(f2.tarifa_regular, 0))::numeric
    end as tarifa_total,
    row_number() over (
      partition by o.ruta_id, o.sentido, rp2_board.ruta_id, rp2_board.sentido
      order by
        (
          greatest(1, round((o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m) / 80.0))
          + coalesce(freq1.espera_promedio_min, p_espera_default_min)
          + coalesce(freq2.espera_promedio_min, p_espera_default_min)
          + 4
          + coalesce(f1.tarifa_regular / 150.0, 0)
          + coalesce(f2.tarifa_regular / 150.0, 0)
        ) asc,
        (rp1_alight.orden - o.orden) desc,
        (d.orden - rp2_board.orden) desc
    ) as rn
  from contexto c
  join allow_transfer_search ats
    on ats.run_transfer
  join origin_candidates o on true
  join public.ruta_paradas rp1_alight
    on rp1_alight.ruta_id = o.ruta_id
   and rp1_alight.sentido = o.sentido
   and rp1_alight.es_bajada = true
   and rp1_alight.orden > o.orden
  join public.paradas p1_alight
    on p1_alight.id = rp1_alight.parada_id
   and p1_alight.activo = true
  join transbordos_expandido tx
    on tx.parada_origen_id = rp1_alight.parada_id
  join public.ruta_paradas rp2_board
    on rp2_board.parada_id = tx.parada_destino_id
   and rp2_board.es_subida = true
   and rp2_board.ruta_id <> o.ruta_id
  join public.paradas p2_board
    on p2_board.id = rp2_board.parada_id
   and p2_board.activo = true
  join destination_route_scope drs
    on drs.ruta_id = rp2_board.ruta_id
   and drs.sentido = rp2_board.sentido
  join public.rutas r2
    on r2.id = rp2_board.ruta_id
  join destination_candidates d
    on d.ruta_id = rp2_board.ruta_id
   and d.sentido = rp2_board.sentido
   and d.orden > rp2_board.orden
  left join latest_fares f1
    on f1.codigo_ruta_key = upper(trim(o.ruta_codigo))
  left join latest_fares f2
    on f2.codigo_ruta_key = upper(trim(r2.codigo_ctp))
  left join lateral (
    select
      rf.frecuencia_promedio_min,
      rf.espera_promedio_min
    from public.ruta_frecuencias rf
    where rf.ruta_id = o.ruta_id
      and rf.activo = true
      and rf.dia_tipo = c.dia_tipo_actual
      and c.hora_local >= rf.hora_inicio
      and c.hora_local < rf.hora_fin
      and rf.sentido in (o.sentido, 'ambos')
    order by case when rf.sentido = o.sentido then 0 else 1 end, rf.hora_inicio desc
    limit 1
  ) freq1 on true
  left join lateral (
    select
      rf.frecuencia_promedio_min,
      rf.espera_promedio_min
    from public.ruta_frecuencias rf
    where rf.ruta_id = rp2_board.ruta_id
      and rf.activo = true
      and rf.dia_tipo = c.dia_tipo_actual
      and c.hora_local >= rf.hora_inicio
      and c.hora_local < rf.hora_fin
      and rf.sentido in (rp2_board.sentido, 'ambos')
    order by case when rf.sentido = rp2_board.sentido then 0 else 1 end, rf.hora_inicio desc
    limit 1
  ) freq2 on true
  where p_sentido is null or rp2_board.sentido = p_sentido
),
plans as (
  select
    tipo_viaje,
    transbordos,
    score,
    ruta_1_id,
    ruta_1_nombre,
    ruta_1_codigo,
    ruta_1_operador,
    sentido_1,
    subida_1_parada_id,
    subida_1_parada_nombre,
    subida_1_distancia_m,
    bajada_1_parada_id,
    bajada_1_parada_nombre,
    ruta_2_id,
    ruta_2_nombre,
    ruta_2_codigo,
    ruta_2_operador,
    sentido_2,
    subida_2_parada_id,
    subida_2_parada_nombre,
    bajada_2_parada_id,
    bajada_2_parada_nombre,
    transbordo_distancia_m,
    destino_distancia_final_m,
    caminata_total_m,
    tiempo_caminando_total_min,
    espera_1_min,
    espera_2_min,
    espera_total_min,
    frecuencia_1_min,
    frecuencia_2_min,
    dia_tipo_aplicado,
    hora_local_aplicada,
    tarifa_total
  from direct_best

  union all

  select
    tipo_viaje,
    transbordos,
    score,
    ruta_1_id,
    ruta_1_nombre,
    ruta_1_codigo,
    ruta_1_operador,
    sentido_1,
    subida_1_parada_id,
    subida_1_parada_nombre,
    subida_1_distancia_m,
    bajada_1_parada_id,
    bajada_1_parada_nombre,
    ruta_2_id,
    ruta_2_nombre,
    ruta_2_codigo,
    ruta_2_operador,
    sentido_2,
    subida_2_parada_id,
    subida_2_parada_nombre,
    bajada_2_parada_id,
    bajada_2_parada_nombre,
    transbordo_distancia_m,
    destino_distancia_final_m,
    caminata_total_m,
    tiempo_caminando_total_min,
    espera_1_min,
    espera_2_min,
    espera_total_min,
    frecuencia_1_min,
    frecuencia_2_min,
    dia_tipo_aplicado,
    hora_local_aplicada,
    tarifa_total
  from transfer_ranked
  where rn = 1
)
select *
from plans
order by
  score asc,
  transbordos asc,
  espera_total_min asc,
  caminata_total_m asc
limit greatest(1, least(p_max_resultados, 50));
$$;

grant execute on function public.buscar_viajes_0_1_transbordo_v2(
  double precision,
  double precision,
  double precision,
  double precision,
  integer,
  integer,
  integer,
  integer,
  text,
  timestamptz,
  boolean,
  integer
) to anon, authenticated;

comment on function public.buscar_viajes_0_1_transbordo_v2(
  double precision,
  double precision,
  double precision,
  double precision,
  integer,
  integer,
  integer,
  integer,
  text,
  timestamptz,
  boolean,
  integer
) is
  'Version 2 del buscador de viajes con 0 o 1 transbordo. Suma espera promedio por frecuencia al score y prioriza opciones mas realistas operativamente.';
