set search_path = public, extensions;

create table if not exists public.stop_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  report_type text not null default 'missing_stop',
  status text not null default 'pending',
  descripcion text not null,
  reported_stop_name text,
  suggested_route_name text,
  latitude double precision,
  longitude double precision,
  context_destination_name text,
  context_route_name text,
  context_route_code text,
  source text not null default 'mobile_manual',
  review_notes text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_reports_report_type_chk'
      and conrelid = 'public.stop_reports'::regclass
  ) then
    alter table public.stop_reports
      add constraint stop_reports_report_type_chk
      check (
        report_type in (
          'missing_stop',
          'stop_moved',
          'stop_name_error',
          'stop_removed',
          'route_change',
          'other'
        )
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_reports_status_chk'
      and conrelid = 'public.stop_reports'::regclass
  ) then
    alter table public.stop_reports
      add constraint stop_reports_status_chk
      check (status in ('pending', 'reviewed', 'approved', 'rejected'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_reports_source_chk'
      and conrelid = 'public.stop_reports'::regclass
  ) then
    alter table public.stop_reports
      add constraint stop_reports_source_chk
      check (source in ('mobile_manual', 'internal_review', 'import'));
  end if;
end $$;

create index if not exists stop_reports_user_created_idx
  on public.stop_reports (user_id, created_at desc);

create index if not exists stop_reports_status_idx
  on public.stop_reports (status, created_at desc);

drop trigger if exists set_updated_at_stop_reports on public.stop_reports;
create trigger set_updated_at_stop_reports
before update on public.stop_reports
for each row
execute function public.set_updated_at();

alter table public.stop_reports enable row level security;

grant select, insert on public.stop_reports to authenticated;

drop policy if exists stop_reports_insert_authenticated on public.stop_reports;
create policy stop_reports_insert_authenticated
on public.stop_reports
for insert
to authenticated
with check (
  auth.uid() = user_id
  and status = 'pending'
  and reviewed_by is null
  and reviewed_at is null
);

drop policy if exists stop_reports_select_own_authenticated on public.stop_reports;
create policy stop_reports_select_own_authenticated
on public.stop_reports
for select
to authenticated
using (auth.uid() = user_id);

comment on table public.stop_reports is
  'Reportes manuales de paradas y cambios de ruta enviados desde la app para revision posterior.';
