set search_path = public, extensions;

create table if not exists public.stop_change_drafts (
  id bigint generated by default as identity primary key,
  action_type text not null,
  parada_id bigint references public.paradas(id) on delete set null,
  ruta_id integer references public.rutas(id) on delete set null,
  sentido text,
  status text not null default 'draft',
  geometry jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  notes text,
  source text not null default 'stop_editor',
  created_by uuid not null references auth.users(id) on delete cascade,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_change_drafts_action_type_chk'
      and conrelid = 'public.stop_change_drafts'::regclass
  ) then
    alter table public.stop_change_drafts
      add constraint stop_change_drafts_action_type_chk
      check (
        action_type in (
          'create_stop',
          'move_stop',
          'rename_stop',
          'deactivate_stop',
          'attach_stop_to_route',
          'detach_stop_from_route'
        )
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_change_drafts_sentido_chk'
      and conrelid = 'public.stop_change_drafts'::regclass
  ) then
    alter table public.stop_change_drafts
      add constraint stop_change_drafts_sentido_chk
      check (
        sentido is null
        or sentido in ('ida', 'vuelta', 'loop', 'ambos', 'sin_definir')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_change_drafts_status_chk'
      and conrelid = 'public.stop_change_drafts'::regclass
  ) then
    alter table public.stop_change_drafts
      add constraint stop_change_drafts_status_chk
      check (status in ('draft', 'reviewed', 'applied', 'rejected'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'stop_change_drafts_source_chk'
      and conrelid = 'public.stop_change_drafts'::regclass
  ) then
    alter table public.stop_change_drafts
      add constraint stop_change_drafts_source_chk
      check (source in ('stop_editor', 'report_review', 'internal'));
  end if;
end $$;

create index if not exists stop_change_drafts_route_status_idx
  on public.stop_change_drafts (ruta_id, status, created_at desc);

create index if not exists stop_change_drafts_stop_status_idx
  on public.stop_change_drafts (parada_id, status, created_at desc);

create index if not exists stop_change_drafts_action_status_idx
  on public.stop_change_drafts (action_type, status, created_at desc);

drop trigger if exists set_updated_at_stop_change_drafts on public.stop_change_drafts;
create trigger set_updated_at_stop_change_drafts
before update on public.stop_change_drafts
for each row
execute function public.set_updated_at();

alter table public.stop_change_drafts enable row level security;

grant select, insert, update, delete on public.stop_change_drafts to authenticated;

drop policy if exists stop_change_drafts_select_authenticated on public.stop_change_drafts;
create policy stop_change_drafts_select_authenticated
on public.stop_change_drafts
for select
to authenticated
using (true);

drop policy if exists stop_change_drafts_insert_authenticated on public.stop_change_drafts;
create policy stop_change_drafts_insert_authenticated
on public.stop_change_drafts
for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists stop_change_drafts_update_authenticated on public.stop_change_drafts;
create policy stop_change_drafts_update_authenticated
on public.stop_change_drafts
for update
to authenticated
using (true)
with check (true);

drop policy if exists stop_change_drafts_delete_authenticated on public.stop_change_drafts;
create policy stop_change_drafts_delete_authenticated
on public.stop_change_drafts
for delete
to authenticated
using (auth.uid() = created_by and status = 'draft');

create or replace function public._shift_ruta_paradas_for_insert(
  p_ruta_id bigint,
  p_sentido text,
  p_target_order integer
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_target integer := greatest(0, coalesce(p_target_order, 0));
begin
  update public.ruta_paradas
  set orden = orden + 1000000
  where ruta_id = p_ruta_id
    and sentido = p_sentido
    and orden >= v_target;

  update public.ruta_paradas
  set orden = orden - 999999
  where ruta_id = p_ruta_id
    and sentido = p_sentido
    and orden >= v_target + 1000000;
end;
$$;

create or replace function public._shift_ruta_paradas_for_delete(
  p_ruta_id bigint,
  p_sentido text,
  p_deleted_order integer
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_deleted integer := greatest(0, coalesce(p_deleted_order, 0));
begin
  update public.ruta_paradas
  set orden = orden + 1000000
  where ruta_id = p_ruta_id
    and sentido = p_sentido
    and orden > v_deleted;

  update public.ruta_paradas
  set orden = orden - 1000001
  where ruta_id = p_ruta_id
    and sentido = p_sentido
    and orden > v_deleted + 1000000;
end;
$$;

revoke all on function public._shift_ruta_paradas_for_insert(bigint, text, integer) from public, anon, authenticated;
revoke all on function public._shift_ruta_paradas_for_delete(bigint, text, integer) from public, anon, authenticated;

create or replace function public.sugerir_insercion_parada_en_ruta(
  p_ruta_id integer,
  p_lat double precision,
  p_lng double precision,
  p_sentido text default 'ambos'
)
returns table (
  ruta_id integer,
  sentido text,
  suggested_order integer,
  before_orden integer,
  before_parada_id bigint,
  before_parada_nombre text,
  after_orden integer,
  after_parada_id bigint,
  after_parada_nombre text,
  total_stops integer,
  distancia_trazado_m integer,
  distancia_prev_m integer,
  distancia_next_m integer,
  progreso_fraccion numeric
)
language sql
stable
set search_path = public, extensions
as $$
with route_line as (
  select
    rp.ruta_id,
    st_makeline(
      st_setsrid(st_makepoint(rp.lng, rp.lat), 4326)
      order by coalesce(rp.segmento_id, 0), coalesce(rp.orden, 0)
    ) as geom
  from public.ruta_puntos rp
  where rp.ruta_id = p_ruta_id
    and rp.lat is not null
    and rp.lng is not null
  group by rp.ruta_id
  having count(*) >= 2
),
requested_senses as (
  select sense as sentido
  from (
    select distinct rp.sentido as sense
    from public.ruta_paradas rp
    where rp.ruta_id = p_ruta_id
      and (
        case
          when coalesce(p_sentido, 'ambos') in ('ida', 'vuelta', 'loop')
            then rp.sentido = p_sentido
          else rp.sentido in ('ida', 'vuelta', 'loop')
        end
      )
    union all
    select
      case
        when coalesce(p_sentido, 'ambos') in ('ida', 'vuelta', 'loop') then p_sentido
        else 'ida'
      end
    where not exists (
      select 1
      from public.ruta_paradas rp
      where rp.ruta_id = p_ruta_id
        and (
          case
            when coalesce(p_sentido, 'ambos') in ('ida', 'vuelta', 'loop')
              then rp.sentido = p_sentido
            else rp.sentido in ('ida', 'vuelta', 'loop')
          end
        )
    )
  ) senses
),
target as (
  select
    rl.ruta_id,
    rs.sentido,
    st_setsrid(st_makepoint(p_lng, p_lat), 4326)::geography as point_geo,
    rl.geom,
    st_distance(
      st_setsrid(st_makepoint(p_lng, p_lat), 4326)::geography,
      rl.geom::geography
    )::integer as distancia_trazado_m,
    st_linelocatepoint(
      rl.geom,
      st_setsrid(st_makepoint(p_lng, p_lat), 4326)
    ) as point_fraction
  from route_line rl
  cross join requested_senses rs
),
route_stops as (
  select
    t.ruta_id,
    t.sentido,
    rp.orden,
    rp.parada_id,
    coalesce(p.nombre, 'Parada de buses') as parada_nombre,
    p.geo,
    st_linelocatepoint(t.geom, p.geo::geometry) as stop_fraction
  from target t
  join public.ruta_paradas rp
    on rp.ruta_id = t.ruta_id
   and rp.sentido = t.sentido
  join public.paradas p
    on p.id = rp.parada_id
),
prev_stop as (
  select distinct on (rs.sentido)
    rs.sentido,
    rs.orden,
    rs.parada_id,
    rs.parada_nombre,
    st_distance(t.point_geo, rs.geo)::integer as distancia_stop_m
  from target t
  join route_stops rs
    on rs.sentido = t.sentido
   and rs.stop_fraction <= t.point_fraction
  order by rs.sentido, rs.stop_fraction desc, rs.orden desc
),
next_stop as (
  select distinct on (rs.sentido)
    rs.sentido,
    rs.orden,
    rs.parada_id,
    rs.parada_nombre,
    st_distance(t.point_geo, rs.geo)::integer as distancia_stop_m
  from target t
  join route_stops rs
    on rs.sentido = t.sentido
   and rs.stop_fraction >= t.point_fraction
  order by rs.sentido, rs.stop_fraction asc, rs.orden asc
),
stop_totals as (
  select
    rs.sentido,
    count(*)::integer as total_stops
  from route_stops rs
  group by rs.sentido
)
select
  t.ruta_id,
  t.sentido,
  case
    when ns.orden is not null then ns.orden
    when ps.orden is not null then ps.orden + 1
    else 0
  end as suggested_order,
  ps.orden as before_orden,
  ps.parada_id as before_parada_id,
  ps.parada_nombre as before_parada_nombre,
  ns.orden as after_orden,
  ns.parada_id as after_parada_id,
  ns.parada_nombre as after_parada_nombre,
  coalesce(st.total_stops, 0) as total_stops,
  t.distancia_trazado_m,
  ps.distancia_stop_m as distancia_prev_m,
  ns.distancia_stop_m as distancia_next_m,
  round((t.point_fraction::numeric), 6) as progreso_fraccion
from target t
left join prev_stop ps
  on ps.sentido = t.sentido
left join next_stop ns
  on ns.sentido = t.sentido
left join stop_totals st
  on st.sentido = t.sentido
order by
  case t.sentido
    when 'ida' then 1
    when 'vuelta' then 2
    when 'loop' then 3
    else 4
  end;
$$;

grant execute on function public.sugerir_insercion_parada_en_ruta(integer, double precision, double precision, text)
  to authenticated;

create or replace function public.aplicar_stop_change_draft(
  p_draft_id bigint
)
returns table (
  draft_id bigint,
  action_type text,
  parada_id bigint,
  ruta_id integer,
  affected_route_links integer,
  status text
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_draft public.stop_change_drafts%rowtype;
  v_user_id uuid := auth.uid();
  v_now timestamptz := timezone('utc', now());
  v_coords jsonb;
  v_lat double precision;
  v_lng double precision;
  v_stop_name text;
  v_stop_id bigint;
  v_route_id integer;
  v_assignments jsonb := '[]'::jsonb;
  v_assignment jsonb;
  v_requested_sentido text;
  v_es_subida boolean;
  v_es_bajada boolean;
  v_target_order integer;
  v_effective_sentido text;
  v_existing_order integer;
  v_selected_route_stop_id bigint;
  v_selected_route_stop_order integer;
  v_selected_route_stop_sentido text;
  v_rows integer := 0;
  v_base_metadata jsonb;
  v_existing_senses text[];
begin
  if v_user_id is null then
    raise exception 'Debes iniciar sesion para aplicar un borrador de parada';
  end if;

  select *
  into v_draft
  from public.stop_change_drafts d
  where d.id = p_draft_id;

  if not found then
    raise exception 'No existe el borrador de parada %', p_draft_id;
  end if;

  v_route_id := v_draft.ruta_id;
  v_stop_id := v_draft.parada_id;
  v_stop_name := nullif(trim(coalesce(v_draft.payload->>'stop_name', '')), '');
  v_base_metadata := coalesce(v_draft.payload->'stop_metadata', '{}'::jsonb);
  v_selected_route_stop_id := nullif(v_draft.payload->>'selected_route_stop_id', '')::bigint;

  if coalesce(v_draft.geometry->>'type', '') = 'Point' then
    v_coords := v_draft.geometry->'coordinates';
  elsif coalesce(v_draft.geometry->>'type', '') = 'FeatureCollection' then
    select feature->'geometry'->'coordinates'
    into v_coords
    from jsonb_array_elements(coalesce(v_draft.geometry->'features', '[]'::jsonb)) feature
    where coalesce(feature->'geometry'->>'type', '') = 'Point'
    limit 1;
  end if;

  if v_coords is not null and jsonb_typeof(v_coords) = 'array' then
    v_lng := nullif(v_coords->>0, '')::double precision;
    v_lat := nullif(v_coords->>1, '')::double precision;
  else
    v_lng := nullif(v_draft.payload->>'lng', '')::double precision;
    v_lat := nullif(v_draft.payload->>'lat', '')::double precision;
  end if;

  if v_draft.action_type in ('create_stop', 'move_stop') and (v_lat is null or v_lng is null) then
    raise exception 'El borrador % necesita una geometria Point valida', p_draft_id;
  end if;

  if v_draft.action_type in ('move_stop', 'rename_stop', 'deactivate_stop', 'attach_stop_to_route', 'detach_stop_from_route')
     and v_stop_id is null then
    raise exception 'El borrador % necesita una parada existente', p_draft_id;
  end if;

  if v_draft.action_type = 'create_stop' then
    insert into public.paradas (
      lat,
      lng,
      nombre,
      operador,
      rutas_red,
      activo,
      fuente,
      metadata,
      created_at,
      updated_at
    )
    values (
      v_lat::numeric,
      v_lng::numeric,
      v_stop_name,
      null,
      null,
      true,
      'manual',
      coalesce(v_base_metadata, '{}'::jsonb) || jsonb_build_object(
        'created_from_stop_change_draft_id', p_draft_id,
        'created_by', v_user_id,
        'created_at', v_now,
        'needs_name', v_stop_name is null,
        'display_name_fallback', case when v_stop_name is null then 'Parada de buses' else null end
      ),
      v_now,
      v_now
    )
    returning id into v_stop_id;
  elsif v_draft.action_type = 'move_stop' then
    update public.paradas
    set
      lat = v_lat::numeric,
      lng = v_lng::numeric,
      nombre = coalesce(v_stop_name, nombre),
      fuente = case when fuente = 'osm' then 'manual' else fuente end,
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
        'moved_from_stop_change_draft_id', p_draft_id,
        'moved_by', v_user_id,
        'moved_at', v_now
      ),
      updated_at = v_now
    where id = v_stop_id;
  elsif v_draft.action_type = 'rename_stop' then
    if v_stop_name is null then
      raise exception 'El borrador % necesita stop_name para renombrar', p_draft_id;
    end if;

    update public.paradas
    set
      nombre = v_stop_name,
      fuente = case when fuente = 'osm' then 'manual' else fuente end,
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
        'renamed_from_stop_change_draft_id', p_draft_id,
        'renamed_by', v_user_id,
        'renamed_at', v_now,
        'needs_name', false
      ),
      updated_at = v_now
    where id = v_stop_id;
  elsif v_draft.action_type = 'deactivate_stop' then
    update public.paradas
    set
      activo = false,
      fuente = case when fuente = 'osm' then 'manual' else fuente end,
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
        'deactivated_from_stop_change_draft_id', p_draft_id,
        'deactivated_by', v_user_id,
        'deactivated_at', v_now
      ),
      updated_at = v_now
    where id = v_stop_id;
  end if;

  if v_draft.payload ? 'route_assignments' then
    v_assignments := coalesce(v_draft.payload->'route_assignments', '[]'::jsonb);
  elsif v_draft.action_type in ('create_stop', 'attach_stop_to_route') and v_route_id is not null then
    v_assignments := jsonb_build_array(
      jsonb_build_object(
        'sentido', coalesce(nullif(v_draft.sentido, ''), 'ida'),
        'target_order', coalesce((v_draft.payload->>'target_order')::integer, 0),
        'es_subida', coalesce((v_draft.payload->>'es_subida')::boolean, true),
        'es_bajada', coalesce((v_draft.payload->>'es_bajada')::boolean, true)
      )
    );
  end if;

  if jsonb_typeof(v_assignments) <> 'array' then
    v_assignments := '[]'::jsonb;
  end if;

  if v_draft.action_type in ('create_stop', 'attach_stop_to_route') then
    for v_assignment in
      select value
      from jsonb_array_elements(v_assignments)
    loop
      v_requested_sentido := coalesce(nullif(v_assignment->>'sentido', ''), coalesce(v_draft.sentido, 'ida'));
      v_es_subida := coalesce((v_assignment->>'es_subida')::boolean, true);
      v_es_bajada := coalesce((v_assignment->>'es_bajada')::boolean, true);
      v_target_order := greatest(0, coalesce((v_assignment->>'target_order')::integer, 0));

      if v_route_id is null then
        raise exception 'El borrador % necesita ruta_id para asociar una parada', p_draft_id;
      end if;

      if v_requested_sentido = 'ambos' then
        select array_agg(distinct rp.sentido order by rp.sentido)
        into v_existing_senses
        from public.ruta_paradas rp
        where rp.ruta_id = v_route_id
          and rp.sentido in ('ida', 'vuelta', 'loop');

        if coalesce(array_length(v_existing_senses, 1), 0) = 0 then
          v_existing_senses := array['ambos'];
        end if;
      else
        v_existing_senses := array[v_requested_sentido];
      end if;

      foreach v_effective_sentido in array v_existing_senses
      loop
        perform public._shift_ruta_paradas_for_insert(v_route_id, v_effective_sentido, v_target_order);

        insert into public.ruta_paradas (
          ruta_id,
          parada_id,
          sentido,
          orden,
          es_subida,
          es_bajada,
          distancia_acumulada_m,
          tiempo_estimado_desde_inicio_min,
          created_at,
          updated_at
        )
        values (
          v_route_id,
          v_stop_id,
          v_effective_sentido,
          v_target_order,
          v_es_subida,
          v_es_bajada,
          null,
          null,
          v_now,
          v_now
        );

        v_rows := v_rows + 1;
      end loop;
    end loop;
  elsif v_draft.action_type = 'detach_stop_from_route' then
    if v_route_id is null then
      raise exception 'El borrador % necesita ruta_id para desasociar una parada', p_draft_id;
    end if;

    if v_selected_route_stop_id is not null then
      select rp.orden, rp.sentido
      into v_selected_route_stop_order, v_selected_route_stop_sentido
      from public.ruta_paradas rp
      where rp.id = v_selected_route_stop_id
        and rp.ruta_id = v_route_id
        and rp.parada_id = v_stop_id
      limit 1;

      if not found then
        raise exception 'La asociacion de ruta_paradas % ya no existe o no coincide con el borrador %', v_selected_route_stop_id, p_draft_id;
      end if;

      delete from public.ruta_paradas
      where id = v_selected_route_stop_id;

      perform public._shift_ruta_paradas_for_delete(v_route_id, v_selected_route_stop_sentido, v_selected_route_stop_order);
      v_rows := v_rows + 1;
    else
      for v_assignment in
        select value
        from jsonb_array_elements(
          case
            when jsonb_typeof(v_assignments) = 'array' and jsonb_array_length(v_assignments) > 0
              then v_assignments
            else jsonb_build_array(jsonb_build_object('sentido', coalesce(nullif(v_draft.sentido, ''), 'ambos')))
          end
        )
      loop
        v_requested_sentido := coalesce(nullif(v_assignment->>'sentido', ''), coalesce(v_draft.sentido, 'ambos'));

        if v_requested_sentido = 'ambos' then
          select array_agg(distinct rp.sentido order by rp.sentido)
          into v_existing_senses
          from public.ruta_paradas rp
          where rp.ruta_id = v_route_id
            and rp.parada_id = v_stop_id;

          if coalesce(array_length(v_existing_senses, 1), 0) = 0 then
            v_existing_senses := array['ambos'];
          end if;
        else
          v_existing_senses := array[v_requested_sentido];
        end if;

        foreach v_effective_sentido in array v_existing_senses
        loop
          for v_existing_order in
            select rp.orden
            from public.ruta_paradas rp
            where rp.ruta_id = v_route_id
              and rp.parada_id = v_stop_id
              and rp.sentido = v_effective_sentido
            order by rp.orden desc
          loop
            delete from public.ruta_paradas
            where ruta_id = v_route_id
              and parada_id = v_stop_id
              and sentido = v_effective_sentido
              and orden = v_existing_order;

            perform public._shift_ruta_paradas_for_delete(v_route_id, v_effective_sentido, v_existing_order);
            v_rows := v_rows + 1;
          end loop;
        end loop;
      end loop;
    end if;
  end if;

  update public.stop_change_drafts
  set
    status = 'applied',
    parada_id = coalesce(v_stop_id, v_draft.parada_id),
    reviewed_by = v_user_id,
    reviewed_at = v_now,
    payload = coalesce(payload, '{}'::jsonb) || jsonb_build_object(
      'applied_at', v_now,
      'applied_by', v_user_id,
      'affected_route_links', v_rows
    ),
    updated_at = v_now
  where id = p_draft_id;

  return query
  select
    p_draft_id,
    v_draft.action_type,
    coalesce(v_stop_id, v_draft.parada_id),
    v_route_id,
    v_rows,
    'applied'::text;
end;
$$;

grant execute on function public.aplicar_stop_change_draft(bigint)
  to authenticated;

comment on table public.stop_change_drafts is
  'Borradores internos para crear, mover, renombrar, desactivar o asociar paradas sin tocar produccion de inmediato.';

comment on function public.sugerir_insercion_parada_en_ruta(integer, double precision, double precision, text) is
  'Sugiere entre que paradas y con que orden insertar una parada dentro de una ruta usando ruta_puntos y ruta_paradas.';

comment on function public.aplicar_stop_change_draft(bigint) is
  'Aplica un borrador de parada sobre paradas y/o ruta_paradas, dejando trazabilidad en stop_change_drafts.';
