set search_path = public, extensions;

create extension if not exists postgis with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.paradas (
  id bigint generated by default as identity primary key,
  osm_id text,
  nombre text,
  lat double precision not null,
  lng double precision not null,
  tiene_techo boolean not null default false,
  accesible boolean not null default false,
  activo boolean not null default true,
  fuente text not null default 'manual',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  geo geography(Point, 4326) generated always as (st_setsrid(st_makepoint(lng, lat), 4326)::geography) stored
);

alter table public.paradas
  add column if not exists osm_id text,
  add column if not exists tiene_techo boolean default false,
  add column if not exists accesible boolean default false,
  add column if not exists activo boolean default true,
  add column if not exists fuente text default 'manual',
  add column if not exists metadata jsonb default '{}'::jsonb,
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists updated_at timestamptz default timezone('utc', now());

update public.paradas
set
  tiene_techo = coalesce(tiene_techo, false),
  accesible = coalesce(accesible, false),
  activo = coalesce(activo, true),
  fuente = coalesce(nullif(fuente, ''), 'manual'),
  metadata = coalesce(metadata, '{}'::jsonb),
  created_at = coalesce(created_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, timezone('utc', now()));

alter table public.paradas
  alter column tiene_techo set default false,
  alter column accesible set default false,
  alter column activo set default true,
  alter column fuente set default 'manual',
  alter column metadata set default '{}'::jsonb,
  alter column created_at set default timezone('utc', now()),
  alter column updated_at set default timezone('utc', now());

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'paradas'
      and column_name = 'geo'
  ) then
    alter table public.paradas
      add column geo geography(Point, 4326)
      generated always as (st_setsrid(st_makepoint(lng, lat), 4326)::geography) stored;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'paradas_fuente_chk'
      and conrelid = 'public.paradas'::regclass
  ) then
    alter table public.paradas
      add constraint paradas_fuente_chk
      check (fuente in ('osm', 'manual', 'reporte_usuario', 'importacion', 'sistema'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'paradas_lat_chk'
      and conrelid = 'public.paradas'::regclass
  ) then
    alter table public.paradas
      add constraint paradas_lat_chk
      check (lat between -90 and 90);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'paradas_lng_chk'
      and conrelid = 'public.paradas'::regclass
  ) then
    alter table public.paradas
      add constraint paradas_lng_chk
      check (lng between -180 and 180);
  end if;
end $$;

create table if not exists public.ruta_paradas (
  id bigint generated by default as identity primary key,
  ruta_id bigint not null references public.rutas(id) on delete cascade,
  parada_id bigint not null references public.paradas(id) on delete cascade,
  sentido text not null default 'ida',
  orden integer not null,
  es_subida boolean not null default true,
  es_bajada boolean not null default true,
  distancia_acumulada_m integer,
  tiempo_estimado_desde_inicio_min integer,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint ruta_paradas_orden_unique unique (ruta_id, sentido, orden)
);

alter table public.ruta_paradas
  add column if not exists sentido text default 'ida',
  add column if not exists es_subida boolean default true,
  add column if not exists es_bajada boolean default true,
  add column if not exists distancia_acumulada_m integer,
  add column if not exists tiempo_estimado_desde_inicio_min integer,
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists updated_at timestamptz default timezone('utc', now());

update public.ruta_paradas
set
  sentido = coalesce(nullif(sentido, ''), 'ida'),
  es_subida = coalesce(es_subida, true),
  es_bajada = coalesce(es_bajada, true),
  created_at = coalesce(created_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, timezone('utc', now()));

alter table public.ruta_paradas
  alter column sentido set default 'ida',
  alter column es_subida set default true,
  alter column es_bajada set default true,
  alter column created_at set default timezone('utc', now()),
  alter column updated_at set default timezone('utc', now());

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_paradas_sentido_chk'
      and conrelid = 'public.ruta_paradas'::regclass
  ) then
    alter table public.ruta_paradas
      add constraint ruta_paradas_sentido_chk
      check (sentido in ('ida', 'vuelta', 'loop', 'ambos'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'ruta_paradas_orden_chk'
      and conrelid = 'public.ruta_paradas'::regclass
  ) then
    alter table public.ruta_paradas
      add constraint ruta_paradas_orden_chk
      check (orden >= 0);
  end if;
end $$;

create table if not exists public.transbordos (
  id bigint generated by default as identity primary key,
  parada_origen_id bigint not null references public.paradas(id) on delete cascade,
  parada_destino_id bigint not null references public.paradas(id) on delete cascade,
  distancia_caminando_m integer not null,
  tiempo_caminando_min integer generated always as (
    greatest(1, round(distancia_caminando_m / 80.0))
  ) stored,
  activo boolean not null default true,
  bidireccional boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint transbordos_unique_pair unique (parada_origen_id, parada_destino_id)
);

alter table public.transbordos
  add column if not exists activo boolean default true,
  add column if not exists bidireccional boolean default true,
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists updated_at timestamptz default timezone('utc', now());

update public.transbordos
set
  activo = coalesce(activo, true),
  bidireccional = coalesce(bidireccional, true),
  created_at = coalesce(created_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, timezone('utc', now()));

alter table public.transbordos
  alter column activo set default true,
  alter column bidireccional set default true,
  alter column created_at set default timezone('utc', now()),
  alter column updated_at set default timezone('utc', now());

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'transbordos_distancia_chk'
      and conrelid = 'public.transbordos'::regclass
  ) then
    alter table public.transbordos
      add constraint transbordos_distancia_chk
      check (distancia_caminando_m >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'transbordos_paradas_distintas_chk'
      and conrelid = 'public.transbordos'::regclass
  ) then
    alter table public.transbordos
      add constraint transbordos_paradas_distintas_chk
      check (parada_origen_id <> parada_destino_id);
  end if;
end $$;

create unique index if not exists paradas_osm_id_uidx
  on public.paradas (osm_id)
  where osm_id is not null;

create index if not exists paradas_geo_gix
  on public.paradas
  using gist (geo);

create index if not exists paradas_activas_idx
  on public.paradas (activo)
  where activo = true;

create index if not exists paradas_fuente_idx
  on public.paradas (fuente);

create index if not exists ruta_paradas_ruta_sentido_orden_idx
  on public.ruta_paradas (ruta_id, sentido, orden);

create index if not exists ruta_paradas_parada_idx
  on public.ruta_paradas (parada_id);

create index if not exists ruta_paradas_subida_idx
  on public.ruta_paradas (ruta_id, sentido, orden)
  where es_subida = true;

create index if not exists ruta_paradas_bajada_idx
  on public.ruta_paradas (ruta_id, sentido, orden)
  where es_bajada = true;

create index if not exists ruta_paradas_parada_sentido_ruta_idx
  on public.ruta_paradas (parada_id, sentido, ruta_id, orden);

create index if not exists transbordos_origen_activo_idx
  on public.transbordos (parada_origen_id)
  where activo = true;

create index if not exists transbordos_destino_activo_idx
  on public.transbordos (parada_destino_id)
  where activo = true;

drop trigger if exists set_updated_at_paradas on public.paradas;
create trigger set_updated_at_paradas
before update on public.paradas
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_ruta_paradas on public.ruta_paradas;
create trigger set_updated_at_ruta_paradas
before update on public.ruta_paradas
for each row
execute function public.set_updated_at();

drop trigger if exists set_updated_at_transbordos on public.transbordos;
create trigger set_updated_at_transbordos
before update on public.transbordos
for each row
execute function public.set_updated_at();

alter table public.paradas enable row level security;
alter table public.ruta_paradas enable row level security;
alter table public.transbordos enable row level security;

drop policy if exists paradas_read_public on public.paradas;
create policy paradas_read_public
on public.paradas
for select
to anon, authenticated
using (true);

drop policy if exists ruta_paradas_read_public on public.ruta_paradas;
create policy ruta_paradas_read_public
on public.ruta_paradas
for select
to anon, authenticated
using (true);

drop policy if exists transbordos_read_public on public.transbordos;
create policy transbordos_read_public
on public.transbordos
for select
to anon, authenticated
using (true);

create or replace function public.buscar_viajes_0_1_transbordo(
  p_origen_lat double precision,
  p_origen_lng double precision,
  p_destino_lat double precision,
  p_destino_lng double precision,
  p_radio_origen_m integer default 600,
  p_radio_destino_m integer default 600,
  p_max_caminar_transbordo_m integer default 180,
  p_max_resultados integer default 12,
  p_sentido text default null
)
returns table (
  tipo_viaje text,
  transbordos integer,
  score numeric,
  ruta_1_id bigint,
  ruta_1_nombre text,
  ruta_1_codigo text,
  ruta_1_operador text,
  sentido_1 text,
  subida_1_parada_id bigint,
  subida_1_parada_nombre text,
  subida_1_distancia_m integer,
  bajada_1_parada_id bigint,
  bajada_1_parada_nombre text,
  ruta_2_id bigint,
  ruta_2_nombre text,
  ruta_2_codigo text,
  ruta_2_operador text,
  sentido_2 text,
  subida_2_parada_id bigint,
  subida_2_parada_nombre text,
  bajada_2_parada_id bigint,
  bajada_2_parada_nombre text,
  transbordo_distancia_m integer,
  destino_distancia_final_m integer,
  caminata_total_m integer,
  tiempo_caminando_total_min integer,
  tarifa_total numeric
)
language sql
stable
set search_path = public, extensions
as $$
with
params as (
  select
    st_setsrid(st_makepoint(p_origen_lng, p_origen_lat), 4326)::geography as origen_geo,
    st_setsrid(st_makepoint(p_destino_lng, p_destino_lat), 4326)::geography as destino_geo
),
latest_fares as (
  select distinct on (upper(trim(t.codigo_ruta)))
    upper(trim(t.codigo_ruta)) as codigo_ruta_key,
    t.tarifa_regular
  from public.tarifas t
  where t.codigo_ruta is not null
  order by upper(trim(t.codigo_ruta)), t.fecha_vigencia desc nulls last, t.id desc
),
origin_candidates as (
  select
    rp.ruta_id,
    rp.sentido,
    rp.parada_id,
    rp.orden,
    r.nombre_ruta as ruta_nombre,
    r.codigo_ctp as ruta_codigo,
    r.operador as ruta_operador,
    p.nombre as parada_nombre,
    st_distance(p.geo, params.origen_geo)::integer as origen_distancia_m
  from params
  join public.ruta_paradas rp on true
  join public.paradas p on p.id = rp.parada_id
  join public.rutas r on r.id = rp.ruta_id
  where p.activo = true
    and rp.es_subida = true
    and st_dwithin(p.geo, params.origen_geo, p_radio_origen_m)
    and (p_sentido is null or rp.sentido = p_sentido)
),
destination_candidates as (
  select
    rp.ruta_id,
    rp.sentido,
    rp.parada_id,
    rp.orden,
    r.nombre_ruta as ruta_nombre,
    r.codigo_ctp as ruta_codigo,
    r.operador as ruta_operador,
    p.nombre as parada_nombre,
    st_distance(p.geo, params.destino_geo)::integer as destino_distancia_m
  from params
  join public.ruta_paradas rp on true
  join public.paradas p on p.id = rp.parada_id
  join public.rutas r on r.id = rp.ruta_id
  where p.activo = true
    and rp.es_bajada = true
    and st_dwithin(p.geo, params.destino_geo, p_radio_destino_m)
    and (p_sentido is null or rp.sentido = p_sentido)
),
direct_ranked as (
  select
    'directo'::text as tipo_viaje,
    0 as transbordos,
    (
      (o.origen_distancia_m + d.destino_distancia_m) / 80.0
      + coalesce(f1.tarifa_regular, 0) / 120.0
    )::numeric as score,
    o.ruta_id as ruta_1_id,
    o.ruta_nombre as ruta_1_nombre,
    o.ruta_codigo as ruta_1_codigo,
    o.ruta_operador as ruta_1_operador,
    o.sentido as sentido_1,
    o.parada_id as subida_1_parada_id,
    coalesce(o.parada_nombre, 'Parada de buses') as subida_1_parada_nombre,
    o.origen_distancia_m as subida_1_distancia_m,
    d.parada_id as bajada_1_parada_id,
    coalesce(d.parada_nombre, 'Parada de buses') as bajada_1_parada_nombre,
    null::bigint as ruta_2_id,
    null::text as ruta_2_nombre,
    null::text as ruta_2_codigo,
    null::text as ruta_2_operador,
    null::text as sentido_2,
    null::bigint as subida_2_parada_id,
    null::text as subida_2_parada_nombre,
    null::bigint as bajada_2_parada_id,
    null::text as bajada_2_parada_nombre,
    null::integer as transbordo_distancia_m,
    d.destino_distancia_m as destino_distancia_final_m,
    (o.origen_distancia_m + d.destino_distancia_m)::integer as caminata_total_m,
    greatest(1, round((o.origen_distancia_m + d.destino_distancia_m) / 80.0))::integer as tiempo_caminando_total_min,
    coalesce(f1.tarifa_regular, 0)::numeric as tarifa_total,
    row_number() over (
      partition by o.ruta_id, o.sentido
      order by (o.origen_distancia_m + d.destino_distancia_m) asc, (d.orden - o.orden) desc
    ) as rn
  from origin_candidates o
  join destination_candidates d
    on d.ruta_id = o.ruta_id
   and d.sentido = o.sentido
   and d.orden > o.orden
  left join latest_fares f1
    on f1.codigo_ruta_key = upper(trim(o.ruta_codigo))
),
transbordos_expandido as (
  select
    t.parada_origen_id,
    t.parada_destino_id,
    t.distancia_caminando_m
  from public.transbordos t
  where t.activo = true
    and t.distancia_caminando_m <= p_max_caminar_transbordo_m

  union all

  select
    t.parada_destino_id as parada_origen_id,
    t.parada_origen_id as parada_destino_id,
    t.distancia_caminando_m
  from public.transbordos t
  where t.activo = true
    and t.bidireccional = true
    and t.distancia_caminando_m <= p_max_caminar_transbordo_m
),
transfer_ranked as (
  select
    'transbordo'::text as tipo_viaje,
    1 as transbordos,
    (
      (o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m) / 80.0
      + 9
      + coalesce(f1.tarifa_regular, 0) / 120.0
      + coalesce(f2.tarifa_regular, 0) / 120.0
    )::numeric as score,
    o.ruta_id as ruta_1_id,
    o.ruta_nombre as ruta_1_nombre,
    o.ruta_codigo as ruta_1_codigo,
    o.ruta_operador as ruta_1_operador,
    o.sentido as sentido_1,
    o.parada_id as subida_1_parada_id,
    coalesce(o.parada_nombre, 'Parada de buses') as subida_1_parada_nombre,
    o.origen_distancia_m as subida_1_distancia_m,
    rp1_alight.parada_id as bajada_1_parada_id,
    coalesce(p1_alight.nombre, 'Parada de buses') as bajada_1_parada_nombre,
    rp2_board.ruta_id as ruta_2_id,
    r2.nombre_ruta as ruta_2_nombre,
    r2.codigo_ctp as ruta_2_codigo,
    r2.operador as ruta_2_operador,
    rp2_board.sentido as sentido_2,
    rp2_board.parada_id as subida_2_parada_id,
    coalesce(p2_board.nombre, 'Parada de buses') as subida_2_parada_nombre,
    d.parada_id as bajada_2_parada_id,
    coalesce(d.parada_nombre, 'Parada de buses') as bajada_2_parada_nombre,
    tx.distancia_caminando_m as transbordo_distancia_m,
    d.destino_distancia_m as destino_distancia_final_m,
    (o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m)::integer as caminata_total_m,
    greatest(1, round((o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m) / 80.0))::integer as tiempo_caminando_total_min,
    (coalesce(f1.tarifa_regular, 0) + coalesce(f2.tarifa_regular, 0))::numeric as tarifa_total,
    row_number() over (
      partition by o.ruta_id, o.sentido, rp2_board.ruta_id, rp2_board.sentido
      order by
        (o.origen_distancia_m + tx.distancia_caminando_m + d.destino_distancia_m) asc,
        (rp1_alight.orden - o.orden) desc,
        (d.orden - rp2_board.orden) desc
    ) as rn
  from origin_candidates o
  join public.ruta_paradas rp1_alight
    on rp1_alight.ruta_id = o.ruta_id
   and rp1_alight.sentido = o.sentido
   and rp1_alight.es_bajada = true
   and rp1_alight.orden > o.orden
  join public.paradas p1_alight
    on p1_alight.id = rp1_alight.parada_id
   and p1_alight.activo = true
  join transbordos_expandido tx
    on tx.parada_origen_id = rp1_alight.parada_id
  join public.ruta_paradas rp2_board
    on rp2_board.parada_id = tx.parada_destino_id
   and rp2_board.es_subida = true
   and rp2_board.ruta_id <> o.ruta_id
  join public.paradas p2_board
    on p2_board.id = rp2_board.parada_id
   and p2_board.activo = true
  join public.rutas r2
    on r2.id = rp2_board.ruta_id
  join destination_candidates d
    on d.ruta_id = rp2_board.ruta_id
   and d.sentido = rp2_board.sentido
   and d.orden > rp2_board.orden
  left join latest_fares f1
    on f1.codigo_ruta_key = upper(trim(o.ruta_codigo))
  left join latest_fares f2
    on f2.codigo_ruta_key = upper(trim(r2.codigo_ctp))
  where p_sentido is null or rp2_board.sentido = p_sentido
),
plans as (
  select
    tipo_viaje,
    transbordos,
    score,
    ruta_1_id,
    ruta_1_nombre,
    ruta_1_codigo,
    ruta_1_operador,
    sentido_1,
    subida_1_parada_id,
    subida_1_parada_nombre,
    subida_1_distancia_m,
    bajada_1_parada_id,
    bajada_1_parada_nombre,
    ruta_2_id,
    ruta_2_nombre,
    ruta_2_codigo,
    ruta_2_operador,
    sentido_2,
    subida_2_parada_id,
    subida_2_parada_nombre,
    bajada_2_parada_id,
    bajada_2_parada_nombre,
    transbordo_distancia_m,
    destino_distancia_final_m,
    caminata_total_m,
    tiempo_caminando_total_min,
    tarifa_total
  from direct_ranked
  where rn = 1

  union all

  select
    tipo_viaje,
    transbordos,
    score,
    ruta_1_id,
    ruta_1_nombre,
    ruta_1_codigo,
    ruta_1_operador,
    sentido_1,
    subida_1_parada_id,
    subida_1_parada_nombre,
    subida_1_distancia_m,
    bajada_1_parada_id,
    bajada_1_parada_nombre,
    ruta_2_id,
    ruta_2_nombre,
    ruta_2_codigo,
    ruta_2_operador,
    sentido_2,
    subida_2_parada_id,
    subida_2_parada_nombre,
    bajada_2_parada_id,
    bajada_2_parada_nombre,
    transbordo_distancia_m,
    destino_distancia_final_m,
    caminata_total_m,
    tiempo_caminando_total_min,
    tarifa_total
  from transfer_ranked
  where rn = 1
)
select *
from plans
order by score asc, transbordos asc, caminata_total_m asc
limit greatest(1, least(p_max_resultados, 50));
$$;

grant execute on function public.buscar_viajes_0_1_transbordo(
  double precision,
  double precision,
  double precision,
  double precision,
  integer,
  integer,
  integer,
  integer,
  text
) to anon, authenticated;
