set search_path = public, extensions;

create extension if not exists postgis with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.paradas (
  id integer generated by default as identity primary key,
  osm_id bigint,
  lat numeric not null,
  lng numeric not null,
  nombre text,
  operador text,
  rutas_red text,
  tiene_techo boolean not null default false,
  tiene_banca boolean default false,
  iluminada boolean default false,
  accesible boolean not null default false,
  geog geography(Point, 4326),
  creado_en timestamptz default now(),
  activo boolean not null default true,
  fuente text not null default 'manual',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  geo geography(Point, 4326) generated always as (
    st_setsrid(st_makepoint((lng)::double precision, (lat)::double precision), 4326)::geography
  ) stored
);

create unique index if not exists paradas_osm_id_uidx
  on public.paradas (osm_id)
  where osm_id is not null;

create index if not exists paradas_geo_gix
  on public.paradas using gist (geo);

create index if not exists paradas_activas_idx
  on public.paradas (activo)
  where activo = true;

create table if not exists public.ruta_paradas (
  id bigint generated by default as identity primary key,
  ruta_id bigint not null references public.rutas(id) on delete cascade,
  parada_id bigint not null references public.paradas(id) on delete cascade,
  sentido text not null default 'ida',
  orden integer not null,
  es_subida boolean not null default true,
  es_bajada boolean not null default true,
  distancia_acumulada_m integer,
  tiempo_estimado_desde_inicio_min integer,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint ruta_paradas_orden_unique unique (ruta_id, sentido, orden),
  constraint ruta_paradas_sentido_chk check (sentido in ('ida', 'vuelta', 'loop', 'ambos')),
  constraint ruta_paradas_orden_chk check (orden >= 0)
);

create index if not exists ruta_paradas_ruta_sentido_orden_idx
  on public.ruta_paradas (ruta_id, sentido, orden);

create index if not exists ruta_paradas_parada_idx
  on public.ruta_paradas (parada_id);

create index if not exists ruta_paradas_subida_idx
  on public.ruta_paradas (ruta_id, sentido, orden)
  where es_subida = true;

create index if not exists ruta_paradas_bajada_idx
  on public.ruta_paradas (ruta_id, sentido, orden)
  where es_bajada = true;

create table if not exists public.transbordos (
  id bigint generated by default as identity primary key,
  parada_origen_id bigint not null references public.paradas(id) on delete cascade,
  parada_destino_id bigint not null references public.paradas(id) on delete cascade,
  distancia_caminando_m integer not null,
  tiempo_caminando_min integer generated always as (
    greatest(1, round(distancia_caminando_m / 80.0))
  ) stored,
  activo boolean not null default true,
  bidireccional boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint transbordos_unique_pair unique (parada_origen_id, parada_destino_id),
  constraint transbordos_distancia_chk check (distancia_caminando_m >= 0),
  constraint transbordos_paradas_distintas_chk check (parada_origen_id <> parada_destino_id)
);

create index if not exists transbordos_origen_activo_idx
  on public.transbordos (parada_origen_id)
  where activo = true;

create index if not exists transbordos_destino_activo_idx
  on public.transbordos (parada_destino_id)
  where activo = true;

drop trigger if exists set_updated_at_paradas on public.paradas;
create trigger set_updated_at_paradas
before update on public.paradas
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_ruta_paradas on public.ruta_paradas;
create trigger set_updated_at_ruta_paradas
before update on public.ruta_paradas
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_transbordos on public.transbordos;
create trigger set_updated_at_transbordos
before update on public.transbordos
for each row execute function public.set_updated_at();

alter table public.paradas enable row level security;
alter table public.ruta_paradas enable row level security;
alter table public.transbordos enable row level security;

grant select on public.paradas to anon, authenticated;
grant select on public.ruta_paradas to anon, authenticated;
grant select on public.transbordos to anon, authenticated;

drop policy if exists paradas_read_public on public.paradas;
create policy paradas_read_public on public.paradas for select to anon, authenticated using (true);

drop policy if exists ruta_paradas_read_public on public.ruta_paradas;
create policy ruta_paradas_read_public on public.ruta_paradas for select to anon, authenticated using (true);

drop policy if exists transbordos_read_public on public.transbordos;
create policy transbordos_read_public on public.transbordos for select to anon, authenticated using (true);

create or replace function public.paradas_por_ruta(p_ruta_id integer, radio_metros integer default 50)
returns table(parada_id integer, nombre text, lat numeric, lng numeric)
language sql
as $$
  select distinct on (p.id)
    p.id, p.nombre, p.lat, p.lng
  from public.paradas p
  join public.ruta_puntos rp
    on st_dwithin(coalesce(p.geog, p.geo), rp.geog, radio_metros)
  where rp.ruta_id = p_ruta_id
  order by p.id;
$$;

create or replace function public.buscar_rutas_cercanas(
  lat_origen double precision,
  lng_origen double precision,
  lat_destino double precision,
  lng_destino double precision,
  radio_metros integer default 500
)
returns table(
  ruta_id integer,
  operador text,
  nombre_ruta text,
  codigo_ctp text,
  dist_origen double precision,
  dist_destino double precision
)
language sql
stable
as $$
  with
  pto as (select st_setsrid(st_makepoint(lng_origen, lat_origen), 4326)::geography as g),
  ptd as (select st_setsrid(st_makepoint(lng_destino, lat_destino), 4326)::geography as g),
  cerca_origen as (
    select rp.ruta_id, min(st_distance(rp.geog, pto.g)) as dist_origen
    from public.ruta_puntos rp, pto
    where st_dwithin(rp.geog, pto.g, radio_metros)
    group by rp.ruta_id
  ),
  cerca_destino as (
    select rp.ruta_id, min(st_distance(rp.geog, ptd.g)) as dist_destino
    from public.ruta_puntos rp, ptd
    where st_dwithin(rp.geog, ptd.g, radio_metros)
    group by rp.ruta_id
  )
  select
    r.id,
    r.operador,
    r.nombre_ruta,
    r.codigo_ctp,
    co.dist_origen,
    cd.dist_destino
  from public.rutas r
  join cerca_origen co on r.id = co.ruta_id
  join cerca_destino cd on r.id = cd.ruta_id
  order by (co.dist_origen + cd.dist_destino)
  limit 15;
$$;

grant execute on function public.paradas_por_ruta(integer, integer) to anon, authenticated;
grant execute on function public.buscar_rutas_cercanas(double precision, double precision, double precision, double precision, integer) to anon, authenticated;
